### ISSUE TITLE
Support for LTS version

### ISSUE THREAD

**Issue by hckhanh** [actions/setup-node#208] opened 2020-10-30 02:02 UTC
For now, I realized that the LTS version on https://nodejs.org/en/ is `14.15.0`
But I always receive the version v12.19.0 on every build. Even though I removed `node-version` param from `actions/setup-node` step:

```yml
jobs:
  push:

    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          check-latest: true
```

So I think that it should have some kind of `lts` version to indicate which version is currently the LTS version.

**Comment by dqn** [comment] 2020-10-31 03:35
I ran into a similar problem.

- actions/setup-node@v1
  - `node-version: 14.x` => v14.14.0
  - `node-version: >=14.15.0` => v15.0.1

**Comment by dqn** [comment] 2020-11-06 01:58
Today, I used actions/setup-node@v1 and see that `node-version: 14.x` becomes v14.15.0.

**Comment by hckhanh** [comment] 2020-11-06 07:20
Maybe the v2 is not quite stable to use.

**Comment by brigolini** [comment] 2020-12-09 11:38
> Today, I used actions/setup-node@v1 and see that `node-version: 14.x` becomes v14.15.0.

I'm having the same problem even when use v1. Might be something I'm doing wrong, I having this as my code:

`      - uses: actions/setup-node@v1
        with:
          node-version: 14.x`

**Comment by smorimoto** [comment] 2020-12-12 03:40
Duplicate of https://github.com/actions/setup-node/issues/26.

**Comment by maxim-lobanov** [comment] 2020-12-16 10:21
Hello everyone!

If you don't provide `node-version` input, this action doesn't setup Node.JS at all and default Image version is used: https://github.com/actions/setup-node/blob/main/src/main.ts#L33
Default image version can be different on different images and it is not recommended to rely on it.

Unfortunately, this action doesn't support `lts` tags yet and this request is tracked by #26 .
So the best solution now is using `14.x` that will point to latest release of Node.JS 14

**Closed** 2021-06-30 13:29 UTC
