### ISSUE TITLE
tar `Cannot mkdir: Permission denied` error at strange path

### ISSUE THREAD

**Issue by mbergal** [actions/setup-node#362] opened 2021-11-19 16:08 UTC
**Description:**

Action fails to restore cache

**Action version:**
`actions/setup-node@v2`

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**
npm 14

**Repro steps:**  
![image](https://user-images.githubusercontent.com/167835/142653213-2b4961f4-a70d-4895-b82a-520b076d2d4c.png)

**Comment by dmitry-shibanov** [comment] 2021-11-22 11:10
Hello @mbergal. Thank you for your report. It looks like a user or tool on your self-hosted runner does not have permissions to write in `/home/ubuntu/.npm/_cacache`. Could you please run your job under the user with appropriate permissions. 

The setup-node action uses [toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache) to save/restore cache. You can try to find similar issue in the [toolkit](https://github.com/actions/toolkit) or [actions/cache](https://github.com/actions/cache) repositories.

**Comment by mbergal** [comment] 2021-11-26 23:14
The command in question `/usr/bin/tar -z -xf cache.tgz -P -C /data/actions-runner/_work/ai-general/ai-general` is trying to create something not in `/home/ubuntu/.npm/_cacache`, but in `data`. Is it expected?

**Comment by dmitry-shibanov** [comment] 2021-11-29 11:20
Hello @mbergal. Thank you for your response. For getting directory for cache we use the `npm config get cache` command. Do you change user or override cache directory (`npm config set cache`) ?

**Comment by dmitry-shibanov** [comment] 2021-12-16 11:51
Hello @mbergal. Do you have any updates or additional information ?

**Comment by dmitry-shibanov** [comment] 2021-12-29 09:41
Hello @mbergal. I'm going to close the issue. We've tried to reproduce from our side, but it works as expected. If you get any additional information or repro steps feel free to ping us.

**Closed by dmitry-shibanov** 2021-12-29 09:41 UTC
Labels: bug
