### ISSUE TITLE
npm cache does not speed up `npm install`

### ISSUE THREAD

**Issue by ugultopu** [actions/setup-node#385] opened 2021-12-21 20:57 UTC
**Description:**
Consider the following builds:

- [3rd build without npm cache](https://github.com/ugultopu/setup-node-without-cache/runs/4597615459?check_suite_focus=true)
- [3rd build with npm cache](https://github.com/ugultopu/setup-node-with-cache/runs/4597616727?check_suite_focus=true)

These two repositories are almost identical, with the only difference being the latter repository caches `npm` via the `setup-node` GitHub Action, whereas the former one does not. In other words, the only difference between the repositories is at the `.github/workflows/main` file:

```yaml
name: Build Pipeline
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '11'
          # Following line is present only on the latter repository
          cache: 'npm'
      - run: npm install
      - run: npm run build
```

Although the build at "setup-node-with-cache" successfully uses npm cache (as evident by the output of the `Run actions/setup-node@v2` step), run time of `Run npm install` step is almost the same as the corresponding step of the build at "setup-node-without-cache".

Isn’t the run time of `Run npm install` step of the build at "setup-node-with-cache" supposed to be significantly shorter than the corresponding step of the build at "setup-node-without-cache", since it is supposed to use the cached npm packages? Am I missing something here?

**Action version:**
2

**Platform:**
Ubuntu

**Runner type:**
Hosted

**Tools version:**
Node 11 and default npm that comes with it.

**Repro steps:**  
- [3rd build without npm cache](https://github.com/ugultopu/setup-node-without-cache/runs/4597615459?check_suite_focus=true)
- [3rd build with npm cache](https://github.com/ugultopu/setup-node-with-cache/runs/4597616727?check_suite_focus=true)

**Expected behavior:**
The `npm install` step of the build that uses the cached npm to be quicker.

**Actual behavior:**
The `npm install` step of the build that uses the cached npm is (virtually) the same as the non-cached version.

**Comment by ugultopu** [comment] 2021-12-21 22:15
Another question is, what is the point of including `package-lock.json` in the cache key? That is, as far as I can tell, if `package-lock.json` changes, the cache will be invalid and hence, all packages will be fetched over the network from scratch.

However, I would say this is pointless, since if `package-lock.json` changes between builds, most likely only one or two new packages are added or removed, compared to the previous build. In other words, most of the packages from the previous build are still being used, even though `package-lock.json` is changed. Hence, the cache would actually still be useful even if `package-lock.json` is changed. However, since the cache will be invalidated (since it depends on `package-lock.json`), we won't be able to benefit from it.

So, what's the point of including `package-lock.json` in the cache key?

**Comment by dmitry-shibanov** [comment] 2021-12-22 12:45
Hello @ugultopu. Thank you for your report. The action setup-node caches saves cache from the global cache directory. The benefit from the caching comes for medium and large size dependencies. Besides, some dependencies are built in runtime, that is why it takes more time.

We use a package-lock.json file, because it contains the exact versions of all dependencies. If some dependencies change the cache can be outdated, that is why we use package-lock.json to track it. Moreover, we use package-lock.json file because it is of the mostly used package's tree dependency file. You can override this behaviour with [cache-dependency-path](https://github.com/actions/setup-node/blob/main/action.yml#L26-L27). We have a [feature request](https://github.com/actions/setup-node/issues/328) with adding restore keys to the action.

For now I'm going to close the issue, because it's an expected behaviour. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-12-22 12:45 UTC
Labels: wontfix

**Comment by sham97** [comment] 2022-11-29 14:48
Hi @dmitry-shibanov ,
i used  - name: Get npm cache directory
        id: npm-cache-dir
        run: |
          echo "::set-output name=dir::$(npm config get cache)"
      - uses: actions/cache@v3
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: install dependencies
        run: npm install
     
      - name: build app
        run: npm run build --if-present
        env:
          CI: ''


this file however cache has been stored in action cache but after i run pipeline it is install dependencies from scratch it gets 1 minute and doesnt use stored cache.

**Comment by sham97** [comment] 2022-11-29 14:49
please can you explain how we can use stored cache for future runs?
