### ISSUE TITLE
Update provided NPM versions for node 15/16 to resolve hanged/stuck npm install

### ISSUE THREAD

**Issue by devminded** [actions/setup-node#490] opened 2022-05-13 15:06 UTC
**Description:**
npm install / npm ci hangs forever due to issues with some npm versions.
May be related to using external registries.

See https://github.com/npm/cli/issues/4028 for reference.
Temporary solution provided in comment works: https://github.com/npm/cli/issues/4028#issuecomment-1121414350
```yaml
      - name: Repair NPM  # Update to latest npm
        run: npm install -g npm
```

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
- node 15 / npm 7.x
- node 16 / npm 8.x

**Repro steps:** 
```yaml
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: npm
```

**Expected behavior:**
Install should work

**Actual behavior:**
Install hangs/gets stuck forever

**Comment by e-korolevskii** [comment] 2022-05-13 15:26
Hi @devminded , 

We will take a look and get back to you as soon as we have some information.

Have a nice day!

**Comment by e-korolevskii** [comment] 2022-05-13 15:26
Hi @devminded , 

We will take a look and get back to you as soon as we have some information.

Have a nice day!

**Comment by dmitry-shibanov** [comment] 2022-05-24 08:13
Hello @devminded. Thank you for your report. If I understood correctly. The root cause of the issue comes from the npm itself. The node comes with its own npm and the npm provided by node can be updated to the latest one after the setup-node action. Besides, we have the feature request with adding npm-version input.

For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed as completed by dmitry-shibanov** 2022-05-24 08:13 UTC
Labels: bug, investigation
