### ISSUE TITLE
Unable to publish to GitHub Package Registry

### ISSUE THREAD

**Issue by daquinoaldo** [actions/setup-node#53] opened 2019-09-04 13:23 UTC
I use the workflow you suggest, but the `npm publish` action on GitHub Package Registry doesn't work. On npmjs it works.

Workflow
```
name: publish

on: release

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm ci
      - run: npm test

  # works
  publish-npm:
    name: Publish NPM
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}

  # doesn't work: tries to publish on https://registry.npmjs.org
  publish-gpr:
    name: Publish GitHub Packages
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

npm publish on npmjs works. On gpr doesn't. Follows the GitHub Action output of the publish-gpr job.

```
Run actions/setup-node@v1
   with:
    registry-url: https://npm.pkg.github.com
    node-version: 10.x
in/tar xzC /home/runner/work/_temp/bc5bc42b-b229-41ac-b8a0-e554467f0c90 -f /home/runner/work/_temp/5cda4e3f-6051-4aaa-b41f-c4761c6cac12
##[add-path]/opt/hostedtoolcache/node/10.16.3/x64/bin
##[set-env name=NPM_CONFIG_USERCONFIG;]/home/runner/work/_temp/.npmrc
##[set-env name=NODE_AUTH_TOKEN;]XXXXX-XXXXX-XXXXX-XXXXX
Added matchers: 'tsc'. Problem matchers scan action output for known warning or error strings and report these inline.
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/tsc.json
Added matchers: 'eslint-stylish'. Problem matchers scan action output for known warning or error strings and report these inline.
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/eslint-stylish.json
Added matchers: 'eslint-compact'. Problem matchers scan action output for known warning or error strings and report these inline.
##[add-matcher]/home/runner/work/_actions/actions/setup-node/v1/.github/eslint-compact.json
```

```
Run npm publish
  npm publish
  shell: /bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***

npm notice [...]
npm notice total files:   18                                      
npm notice 
npm ERR! code E401
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/https-localhost - You must be logged in to publish packages.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2019-09-04T13_02_57_793Z-debug.log
##[error]Process completed with exit code 1.
```

As you can see in Run actions/setup-node@v1 the registry-url is right, in Run npm publish is not.

**Comment by damccorm** [comment] 2019-09-04 18:17
Sorry, misunderstood - any chance you can share your package.json file? Also, are you able to publish to GPR locally with that package.json file?

**Comment by krystof-k** [comment] 2019-09-07 15:19
I'm also having trouble with pushing to GitHub Package Registry. Getting this error:

```bash
  yarn publish
  shell: /bin/bash -e {0}
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: ***
yarn publish v1.17.3
warning package.json: No license field
warning package.json: No license field
[1/4] Bumping version...
info Current version: 0.4.1
[2/4] Logging in...
[3/4] Publishing...
error Couldn't publish package: "https://npm.pkg.github.com/@cloudaper%2ficons: Document update conflict"
info Visit https://yarnpkg.com/en/docs/cli/publish for documentation about this command.
##[error]Process completed with exit code 1.
```

I guess authentication works fine, because when I publish the package locally (which works) it shows another (duplicate) error. Any ideas?

**Comment by PeterHewat** [comment] 2019-09-11 21:08
I have the same issue. I am unable to publish to GitHub Package Registry using GITHUB_TOKEN. The only way I managed to get it working is if I set a secret with a personal access token (PAT).

I have setup up a repo to demonstrate this:
https://github.com/PeterHewat/npm-publish-gpr

This is the content of my action .github/workflows/publish.yml:
```
name: NPM Publish to GitHub Package Registry

on:
  push:
    branches:
      - master
    paths:
      - 'dist/*'

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scope: '@peterhewat'

      - name: Setup GIT
        run: |
          git switch -c master
          git config user.email ""
          git config user.name "Publish Action"

      - name: Bump package.json version
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          npm version patch
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY"

      - name: Publish
        env:
          # NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
          NODE_AUTH_TOKEN: ${{secrets.GPR_PAT}}
        run: npm publish
```
This is my package.json:
```
{
  "name": "@peterhewat/npm-publish-gpr",
  "version": "0.0.13",
  "files": [
    "dist"
  ],
  "publishConfig": {
    "registry": "https://npm.pkg.github.com/"
  }
}
```
With the PAT, the action completes successfully:
https://github.com/PeterHewat/npm-publish-gpr/commit/9e0c3c5b3c20140a99c1754975fcea941dc3a9c3/checks

With GITHUB_TOKEN, I get "npm ERR! 500 Internal Server Error":
https://github.com/PeterHewat/npm-publish-gpr/commit/b2cb688b43ddd5a1a5319588921fb962a37c6ace/checks#step:6:23

The problem is that a PAT is unsuitable since my repo will by inside an enterprise account and I don't want the livelihood of my action to rely on a user setting since users of a team come and go, repos stay...

**Comment by PeterHewat** [comment] 2019-09-11 21:22
> @daquinoaldo doesn't work: tries to publish on https://registry.npmjs.org

Isn't it because you haven't specified the scope ? Checkout my example, it works... but with a PAT, not with the internally provided GITHUB_TOKEN...

**Comment by krystof-k** [comment] 2019-09-12 06:36
@PeterHewat Hmm, interesting, I'll try it with the personal token too. So this seems more as an issue on the GitHub end.

**Comment by Mesta** [comment] 2019-09-18 15:28
Hey,

I faced the same error 500 trying to publish into GPR. It is now fixed since I added `publishConfig` section in `package.json` (c.f. [this documentation](https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry#configuring-a-package-scope-using-publishconfig-in-packagejson))

**Comment by PeterHewat** [comment] 2019-09-19 12:38
@Mesta I already had configured publishConfig in my package.json but still had error 500.
Could you give a link to a working repo please?

**Comment by Mattamorphic** [comment] 2019-09-19 12:44
Just to keep you all informed we are investigating this on both the Actions and Package Registry side of things - and although I don't have an update that we can share yet, we are working on it! ❤️

**Comment by PeterHewat** [comment] 2019-09-19 12:48
@Mattamorphic Excellent :-)

@Mesta You actually managed to publish to GPR using GITHUB_TOKEN ? If so, can you see anything perticularly off in my attempt here: https://github.com/PeterHewat/npm-publish-gpr

**Comment by Mesta** [comment] 2019-09-19 12:54
> @Mesta I already had configured publishConfig in my package.json but still had error 500.
> Could you give a link to a working repo please?
Sorry, I can't as it is a private repository.

I did, but it's not working everytime and I don't understand why. I still will give a look to your attempt.

**Comment by plchampigny** [comment] 2019-09-19 15:05
@Mattamorphic  Just to add more details, I am trying to publish on a private registry related to my organization. Maybe the issue is related to that specific case?

**Comment by denlb** [comment] 2019-09-20 05:29
Same here
[npmpublish.yml](https://github.com/denlb/timer-state-machine/blob/master/.github/workflows/npmpublish.yml#L43)

https://github.com/denlb/timer-state-machine/runs/228613882
```
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/timer-state-machine - You must be logged in to publish packages.
```
Any hints what am I doing wrong? Seems like the `registry-url` was not set to https://npm.pkg.github.com/

**Comment by michaelmerrill** [comment] 2019-09-23 17:26
Any update on this? When using the GITHUB_TOKEN I receive:

`npm ERR! 400 Bad Request - PUT https://npm.pkg.github.com/@<owner>%2f<package-name> - RepoAcceptsPackageUploads: Unauthorized access. Please check to ensure your token has access to read this repository.`

The token should have access to read/write the repo, yeah?

**Comment by okuryu** [comment] 2019-09-24 13:29
Regarding occurs 500 error on publishing, I have been bumped the same error on my repo for a while, but I have confirmed it resolved on my repo today.

It works well with the following workflow:
```yaml
name: Publish
on:
  release:
    types:
      - created
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 10
          registry-url: https://npm.pkg.github.com
          scope: '@okuryu'
      - name: npm publish
        run: |
          LATEST=`npm view . version`
          CURRENT=`cat package.json | jq -r .version`
          if [ "$LATEST" != "$CURRENT" ]
          then
            npm ci
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Also, the following settings are not required:
- the `.npmrc` file is not required
- `publishConfig` in the `package.json` file is not required
- creating and configuring a personal token for your repo is not required

You might want to try publishing to GPR again.

**Comment by PeterHewat** [comment] 2019-09-24 20:00
@okuryu I also confirm that my previously non functional YML scripts now work fine regarding publishing to GPR with GITHUB_TOKEN

**Comment by shaodahong** [comment] 2019-09-25 02:24
> @okuryu I also confirm that my previously non functional YML scripts now work fine regarding publishing to GPR with GITHUB_TOKEN

https://github.com/shaodahong/actions/runs/235078336

I recheck, is also fail, i don't konw what's wrong

**Comment by okuryu** [comment] 2019-09-25 03:15
@shaodahong Try this change:
```diff
diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
index 86194e8..17df8cc 100644
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -10,6 +10,7 @@ jobs:
         with:
           node-version: 10
           registry-url: 'https://npm.pkg.github.com'
-      - run: npm publish --access public
+          scope: '@shaodahong'
+      - run: npm publish
         env:
           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
diff --git a/package.json b/package.json
index de10102..7d0ad50 100644
--- a/package.json
+++ b/package.json
@@ -1,5 +1,5 @@
 {
-  "name": "@dahong/actions",
+  "name": "@shaodahong/actions",
   "version": "0.0.1",
   "main": "index.js",
   "repository": "git@github.com:shaodahong/github-action.git",
```

**Comment by shaodahong** [comment] 2019-09-25 03:24
@okuryu wow, work fine, thank you

and in my see, publish package must with the scope?  the scope that means my name or organnization

**Comment by shaodahong** [comment] 2019-09-25 03:32
guys, [Github Package doc](https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry)

> Note: GitHub Package Registry only supports **scoped NPM packages**. Scoped packages have names with the format of @owner/name. Scoped packages always begin with an @ symbol. You may need to update the name in your package.json to use the scoped name. For example, "name": "@codertocat/hello-world-npm".

**Comment by krystof-k** [comment] 2019-09-25 11:44
Yes, working now without any change to GitHub workflow YAML! 🎉

**Comment by Mesta** [comment] 2019-09-25 11:50
Same for me. I hope the situation is stable🤞

**Comment by bryanmacfarlane** [comment] 2019-10-16 12:17
It looks like this is resolved.  Thanks all!

**Closed by bryanmacfarlane** 2019-10-16 12:17 UTC

**Comment by jwu910** [comment] 2019-11-21 07:35
> [Github Package doc](https://help.github.com/en/articles/configuring-npm-for-use-with-github-package-registry)
> 
> > Note: GitHub Package Registry only supports **scoped NPM packages**. Scoped packages have names with the format of @owner/name. Scoped packages always begin with an @ symbol. You may need to update the name in your package.json to use the scoped name. For example, "name": "@codertocat/hello-world-npm".

If we change a package name to a scoped package name to conform to the GPR constraints, does this change our npm package name when the package gets published to the npm registry too?

**Comment by asbjornu** [comment] 2021-03-17 12:42
The discussion in #73 seems to conclude that `setup-node` only works with scoped packages, which is pretty terrible.

**Comment by mbrowne** [comment] 2021-10-19 19:40
In my case it turned out to be that it was being picky about the format of the `repository` field in `package.json`—but oddly only when running `npm pack` and then running `npm publish` on the tarball (running `npm publish` directly in the root of the repo worked fine). This seems to have only become an issue since upgrading to node 16 (or at least, it's not happening on our other repo that seems to have an otherwise identical setup).

**Comment by maguie** [comment] 2022-09-01 20:31
> Hey folks!
> 
> I found that I had to separate registry setup and registry publishing into separate steps when configuring this: https://gist.github.com/Mattamorphic/792c2f1975c7f96065b9f9fc94311218
> 
> Here's a repository where I applied that: https://github.com/Mattamorphic/github-actions-package-registry-example
> 
> Here's an example of my action being executed: https://github.com/Mattamorphic/github-actions-package-registry-example/commit/5d2e3234123ba83ca8841d498f6e3ebc4ddb9301/checks
> 
> ```yaml
> name: Deploy package to GitHub package registry
> on:
>   pull_request:
>     branches:
>       - master
>   push:
>     branches:
>       - master
> jobs:
>   build:
>     runs-on: ubuntu-latest
>     steps:
>       - name: "Setup actions"
>         uses: actions/checkout@v1
>       - name: "npm/registry setup"
>         uses: actions/setup-node@v1
>         with:
>           node-version: 12
>           registry-url: https://npm.pkg.github.com/
>           scope: "@OWNER"
>         env:
>           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
>       - name: "publish package"
>         uses: actions/bin/debug@master
>         run: |
>           npm run test 
>           npm run build
>           echo @OWNER:registry=https://npm.pkg.github.com/ >> .npmrc
>           npm publish
>         env:
>           NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
> ```
> 
> Notice that the step I have to configure the registry is an entirely separate step to when I am publishing my package. _Also_ that I'm providing the **GITHUB_TOKEN** at the **setup** step as well as at the **publishing** step.
> 
> If you are still seeing a 500 error here, then please do reach out to https://github.com/support and we'll gladly dive into this further :octocat:

It worked for me as well. Thanks for sharing!
