### ISSUE TITLE
registry-url ignored completely

### ISSUE THREAD

**Issue by jektvik** [actions/setup-node#244] opened 2021-03-18 19:56 UTC
Have a setup like this:

```
name: Node.js Package

on:
  push:
    branches:
    - master

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: https://npm.pkg.github.com/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```
And the docs (https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages) say that this should publish to the provided registry-url i.e. to github.
But instead the job tries pushing to npm and my log fails saying that:
```
Not Found - PUT https://registry.npmjs.org/my-package-name - Not found
```
It's my first shot at github actions so not sure if i'm missing something or whether the setup-node action is messed up and doesn't create the npmrc file properly ?

**Comment by joebowbeer** [comment] 2021-03-19 03:23
Please provide package.json and .npmrc file if it exists.

In particular, what are the values of the following in package.json?
* name
* publishConfig
* repository

publishConfig will override.

**Comment by jektvik-si** [comment] 2021-03-19 09:44
On that setup there was no entry for  wither
- publishConfig
- repository
in package.json

the name was unscoped so simply
name: "my-package-name"

**Comment by rafifos** [comment] 2021-03-24 17:05
Providing additional context:

```
  Release:
    runs-on: ubuntu-latest
    needs: Tests
    if: | # Only runs if the current branch is `master`.
      contains('
        refs/heads/master
      ', github.ref)

    steps:
      - name: Checking out repository
        uses: actions/checkout@v2

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"

      - uses: actions/cache@v2.1.4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Use Node.js 14
        uses: actions/setup-node@v2
        with:
          node-version: "14"
          registry-url: ${{ secrets.NPM_REGISTRY }}

      - name: Install dependencies
        run: |
          yarn --pure-lockfile --non-interactive --no-progress

      - name: Restoring Next.js build cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Build project
        run: yarn build

      - name: Run semantic-release
        run: yarn semantic-release
```

`NPM_REGISTRY` contains both the registry url and npm token (like in `.npmrc`, i've ommited the token for obvious reasons)

`//registry.npmjs.org/:_authToken=${NPM_TOKEN}`

And finally, this is the `package.json`:

```
{
  "private": true,
  "name": "project name",
  "version": "1.0.0",
  "publishConfig": {
    "access": "restricted"
  },
  "scripts": {
    "semantic-release": "semantic-release"
  },
  "engines": {
    "node": ">=14"
  },
  "dependencies": {
    "private package only published on npm": "1.0.2"
  }
}
```

**Comment by rafifos** [comment] 2021-03-24 18:51
Update: Echoing `NPM_REGISTRY` to a `.npmrc` in the project root lets Yarn succesfully resolves the package's url.

`echo ${{ secrets.NPM_REGISTRY }} > ${{ github.workspace }}/.npmrc`

**Comment by dmitry-shibanov** [comment] 2021-12-02 09:28
Hello @jektvik. Sorry for the late response. If it's still relevant for you, could you please provide a public repository to reproduce the issue. We've tried by our side, but it works as expected.

Hello @rafifos. Thank you for your response. I think in your case it should work because the setup-node action creates .npmrc file in temp directory and define NPM_CONFIG_USERCONFIG environment variable to use .npmrc file. But the .npmrc file in the root of the project has more precedence than file from NPM_CONFIG_USERCONFIG environment variable, that is why yarn gets configuration from the .npmrc in the root of the project, configuration from package.json and default configuration from yarn.

**Comment by jektvik-si** [comment] 2021-12-02 09:43
@dmitry-shibanov - Pass. I don't even remember which project this was for at this point.

**Comment by dmitry-shibanov** [comment] 2021-12-09 15:50
Hello everyone. For now I'm closing the issue. If you have any concerns feel free to contact us.

**Closed by dmitry-shibanov** 2021-12-09 15:50 UTC
