### ISSUE TITLE
Error trying to use the cache option with yarn v4 and above 

### ISSUE THREAD

**Issue by colenso** [actions/setup-node#904] opened 2023-11-24 07:33 UTC
**Description:**
Throws an error:
`This project's package.json defines "packageManager": "yarn@4.0.2". However the current global version of Yarn is 1.22.21.`

**Action version:**
4.0.0

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Node: v18
Yarn: v4.0.2

**Repro steps:**  
- Upgrade the yarn version in the project to v4 or above which doesn't include the yarn binary in .yarn/releases/
- Use the cache option along with this action
- It should spit out the error I mentioned above.

**Expected behavior:**
It should run successfully.

**Actual behavior:**
It throws the error as above.

**Comment by colenso** [comment] 2023-11-24 07:35
More context:
Our project is currently using the older yarn i.e. classic and I updated it to use modern i.e. v4.0.2

**Comment by nikolai-laevskii** [comment] 2023-11-24 13:57
Thanks for creating the issue and providing detailed repro steps! We will look into it and come back with details!

**Comment by ravenberg** [comment] 2023-12-26 05:57
Underneath the error message you posted was the following hint.

> Presence of the "packageManager" field indicates that the project is meant to be used with Corepack, a tool included by default with all official Node.js distributions starting from 16.9 and 14.19.
Corepack must currently be enabled by running corepack enable in your terminal. For more information, check out https://yarnpkg.com/corepack.

After which I enabled corepack using the command

```
corepack enable
```

And that fixed my issue.

**Comment by dmitry-shibanov** [comment] 2023-12-28 11:07
Hello everyone. For now I'm going to close the issue as duplicate of https://github.com/actions/setup-node/issues/899. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2023-12-28 11:07 UTC
Labels: bug

**Comment by tiavina-mika** [comment] 2024-06-10 10:42
in your yaml workflow file add:
```
      - name: Enable Corepack
        run: corepack enable
```

**Comment by JoseAlban** [comment] 2024-07-29 16:04
> in your yaml workflow file add:
> 
> ```
>       - name: Enable Corepack
>         run: corepack enable
> ```

That worked for me as well :) thanks for sharing

**Comment by hichemfantar** [comment] 2025-02-08 13:04
![Image](https://github.com/user-attachments/assets/851c49f0-9ca9-4867-a953-7abf759efc91)

**Comment by hichemfantar** [comment] 2025-02-08 15:57
this is the PR https://github.com/facebook/react-native-website/pull/4489 if anyone can help me fix it, that'd be great

**Comment by RSP-min** [comment] 2025-02-20 09:41
@hichemfantar 
You must enable Corepack before specifying the Node.js version.

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Enable Corepack // first
        run: corepack enable

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run Lint
        run: yarn ci:lint
        working-directory: website

**Comment by hichemfantar** [comment] 2025-02-20 12:15
@RSP-min thanks! didn't realize the corepack status transferred after setting up a different node release
