### ISSUE TITLE
NPM CI error: nice-napi not accessible from piscina

### ISSUE THREAD

**Issue by ekselys** [actions/setup-node#337] opened 2021-09-25 17:53 UTC
Package.json:
```json
{
    "name": "sample",
    "version": "0.0.1",
    "license": "MIT",
    "engines": {
        "node": "12"
    },
    "scripts": {
        ....some scripts
    },
    "private": true,
    "dependencies": {
        "@angular/animations": "12.2.0",
        "@angular/cdk": "12.2.0",
        "@angular/common": "12.2.0",
        "@angular/compiler": "12.2.0",
        "@angular/core": "12.2.0",
        "@angular/fire": "7.0.0",
        "@angular/forms": "12.2.0",
        "@angular/material": "12.2.0",
        "@angular/platform-browser": "12.2.0",
        "@angular/platform-browser-dynamic": "12.2.0",
        "@angular/router": "12.2.0",
        "@angular/service-worker": "12.2.0",
        "@google-cloud/logging": "9.6.0",
        "@nestjs/axios": "0.0.1",
        "@nestjs/common": "8.0.6",
        "@nestjs/config": "1.0.1",
        "@nestjs/core": "8.0.6",
        "@nestjs/platform-express": "8.0.6",
        "@nrwl/angular": "12.6.5",
        "class-transformer": "0.4.0",
        "class-validator": "0.13.1",
        "cls-hooked": "4.2.2",
        "cookie-parser": "1.4.5",
        "date-fns": "2.23.0",
        "fast-xml-parser": "3.20.0",
        "firebase": "9.0.0",
        "firebase-admin": "9.11.1",
        "firebase-functions": "3.15.4",
        "flat": "5.0.2",
        "helmet": "4.6.0",
        "lodash": "4.17.21",
        "nanoid": "3.1.25",
        "reflect-metadata": "0.1.13",
        "rxfire": "6.0.0",
        "rxjs": "7.3.0",
        "tslib": "2.0.0",
        "zone.js": "0.11.4"
    },
    "devDependencies": {
        "@angular-builders/custom-webpack": "12.1.0",
        "@angular-devkit/architect": "0.1200.0",
        "@angular-devkit/build-angular": "12.2.0",
        "@angular-eslint/eslint-plugin": "12.3.1",
        "@angular-eslint/eslint-plugin-template": "12.3.1",
        "@angular-eslint/template-parser": "12.3.1",
        "@angular/cli": "12.2.0",
        "@angular/compiler-cli": "12.2.0",
        "@angular/language-service": "12.2.0",
        "@firebase/rules-unit-testing": "2.0.0",
        "@firebase/testing": "0.20.11",
        "@nestjs/schematics": "8.0.2",
        "@nestjs/swagger": "5.0.9",
        "@nestjs/testing": "8.0.6",
        "@nrwl/cli": "12.6.5",
        "@nrwl/eslint-plugin-nx": "12.6.5",
        "@nrwl/jest": "12.6.5",
        "@nrwl/linter": "12.6.5",
        "@nrwl/nest": "12.6.5",
        "@nrwl/node": "12.6.5",
        "@nrwl/tao": "12.6.5",
        "@nrwl/workspace": "12.6.5",
        "@types/cls-hooked": "4.3.3",
        "@types/cookie-parser": "1.4.2",
        "@types/flat": "5.0.2",
        "@types/jest": "26.0.24",
        "@types/node": "14.14.33",
        "@types/supertest": "2.0.11",
        "@typescript-eslint/eslint-plugin": "3.9.1",
        "@typescript-eslint/parser": "3.8.0",
        "copy-webpack-plugin": "9.0.1",
        "dotenv": "10.0.0",
        "eslint": "7.22.0",
        "eslint-config-google": "0.14.0",
        "eslint-config-prettier": "8.1.0",
        "eslint-plugin-import": "2.22.0",
        "firebase-functions-test": "0.3.2",
        "firebase-tools": "9.16.6",
        "fuzzy": "0.1.3",
        "inquirer": "6.2.2",
        "inquirer-autocomplete-prompt": "1.0.1",
        "jest": "27.0.3",
        "jest-preset-angular": "9.0.4",
        "jsonc-parser": "3.0.0",
        "ng-packagr": "12.1.0",
        "open": "7.0.3",
        "prettier": "2.3.2",
        "rimraf": "3.0.2",
        "supertest": "6.1.4",
        "swagger-ui-express": "4.1.6",
        "ts-essentials": "7.0.3",
        "ts-jest": "27.0.4",
        "ts-node": "9.1.1",
        "type-fest": "2.3.2",
        "typescript": "4.3.5",
        "webpack": "5.47.0",
        "webpack-merge": "5.8.0",
        "webpack-node-externals": "3.0.0"
    }
}
```

Github action:
```yml
name: Test pull request

on:
  pull_request:
    branches: [ develop ]
    paths-ignore:
      - 'apps/test/**'
      - 'apps/test-e2e/**'
      - 'libs/angular/**'

jobs:
  test_server_pull_request:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 12
      - run: npm ci
      (...more build commands)

```

Then it found in cache the setup-node@master
```
Run actions/setup-node@master
Found in cache @ /opt/hostedtoolcache/node/12.22.6/x64
```

On `npm ci`, the action ends in error:

```
Run npm ci
npm ERR! nice-napi not accessible from piscina

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-09-25T17_41_55_324Z-debug.log
Error: Process completed with exit code 1.
```

This action just stopped working without any change on the code base or its dependencies.
Any clue?

**Comment by ekselys** [comment] 2021-09-29 17:39
UP

**Comment by raitisbe** [comment] 2021-10-15 10:46
+1 having this also on node 14
In our case it was after adding dependency to geotiff.js. Might be just a coincidence

**Comment by raitisbe** [comment] 2021-10-15 18:52
I was able to solve this by 

1. removing node_modules and 
2. removing package-lock.json
3. npm i

**Comment by dmitry-shibanov** [comment] 2021-10-18 07:37
Hello @raitisbe. Thank you for your response. I think the problem is related to links and dependencies in package-lock.json. The `npm ci` command does not change package-lock.json. The `npm i `command can update dependencies, that is why I think the root cause of the issue comes from some of the project's dependencies.

For now I'm closing the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-10-18 07:37 UTC

**Comment by canbax** [comment] 2022-06-07 10:40
I get the same error for my GitHub Action that tries to run cypress end-to-end tests. Below are the logs

> Run cypress-io/github-action@v4
>   with:
>     build: npm run build
>     start: node server.js
>     browser: chrome
>     headless: true
>     record: false
>     component: false
> /usr/bin/docker exec  ab3a4e4d4e51498765f2400b701bd7eb3514414b0aea9fa5404d567b0f898b25 sh -c "cat /etc/*release | grep ^ID"
> /usr/local/bin/npm ci
> npm ERR! code ENOENT
> npm ERR! syscall spawn git
> npm ERR! path git
> npm ERR! errno -2
> npm ERR! enoent Error while executing:
> npm ERR! enoent undefined ls-remote -h -t ssh://git@github.com/iVis-at-Bilkent/cytoscape.js-cise.git
> npm ERR! enoent 
> npm ERR! enoent 
> npm ERR! enoent spawn git ENOENT
> npm ERR! enoent This is related to npm not being able to find a file.
> npm ERR! enoent 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /github/home/.npm/_logs/2022-06-07T08_30_44_416Z-debug.log
> Error: The process '/usr/local/bin/npm' failed with exit code 254

**Comment by canbax** [comment] 2022-06-08 05:53
Hi @IvanZosimov It is a private project, I think you cannot see the link. 

In my case, I observed that if the "_package.json_" dependency is like 

`"cytoscape-cise": "github:iVis-at-Bilkent/cytoscape.js-cise#develop",` this gives error

**Comment by IvanZosimov** [comment] 2022-06-09 09:06
Hello, @canbax 👋 ! Thanks for your answer 🌯  I checked it out on my local machine and NPM throws the same error when I'm trying to install the mentioned dependency from the `develop` branch, which means that the root of this problem isn't in our action. I hope that the use of `master` branch fixed it for you.

**Comment by canbax** [comment] 2022-06-09 10:30
thanks for your efforts @IvanZosimov We couldn't solve this issue and then switched to an alternative way
