### ISSUE TITLE
Windows: Cannot update global npm version after using setup-node

### ISSUE THREAD

**Issue by peterjuras** [actions/setup-node#411] opened 2022-01-29 07:42 UTC
**Description:**
Up until now, updating the global npm version after setting up the node version using `npm install -g npm` worked on all operating systems without issues.

Now I'm receiving the following errors:

```
npm ERR! code EPERM
npm ERR! syscall rename
npm ERR! path C:\npm\prefix\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate
npm ERR! dest C:\npm\prefix\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate
npm ERR! errno -4048
npm ERR! Error: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\npm\prefix\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\npm\prefix\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\npm\prefix\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\npm\prefix\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\npm\\prefix\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!     dest: 'C:\\npm\\prefix\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\npm\\prefix\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!   dest: 'C:\\npm\\prefix\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate',
npm ERR!   parent: 'npm'
npm ERR! }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\npm\cache\_logs\2022-01-29T07_32_14_023Z-debug.log
```

**Action version:**
2.5.1 (pinned at @2)

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [X] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

**Tools version:**
Trying to set up node 12, likely also an issue with other node versions.

**Repro steps:**  

You can see an [example action run here](https://github.com/peterjuras/github-actions-windows-npm-install-test/runs/4989986620?check_suite_focus=true). The failed workflow runs `npm install -g npm` after using the `setup-node` action, the passing run runs it without using the setup-node action.

Workflow configuration used in the example above:
```yaml
name: github-actions-windows-npm-install-test
on:
  push:
jobs:
  win-setup-node-action:
    name: "WIN: Global npm install with setup-node action"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Install latest npm version
        run: npm install --global npm
  win-preinstalled-node:
    name: "WIN: Global npm install without setup-node action"
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install latest npm version
        run: npm install --global npm
``` 

**Expected behavior:**

`npm install -g npm` should globally install the newest npm version and overwrite the default version that comes with node 12, 14 etc.

**Actual behavior:**

`npm install -g npm` fails due to permissions errors on Windows and breaks the workflow run.

**Comment by matt5Github** [comment] 2022-01-29 17:31
I am getting same error.

3365 silly finalize C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp
3366 verbose unlock done using C:\Users\test\AppData\Roaming\npm-cache\_locks\staging-4b3d93efbe81d33a.lock for C:\Users\test\AppData\Roaming\npm\node_modules\.staging
3367 verbose stack Error: EPERM: operation not permitted, rename 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
3368 verbose cwd C:\Users\test\AppData\Roaming
3369 verbose Windows_NT 10.0.19043
3370 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "npm@latest"
3371 verbose node v8.11.4
3372 verbose npm  v5.6.0
3373 error path C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate
3374 error code EPERM
3375 error errno -4048
3376 error syscall rename
3377 error Error: EPERM: operation not permitted, rename 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
3377 error  { Error: EPERM: operation not permitted, rename 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
3377 error   cause:
3377 error    { Error: EPERM: operation not permitted, rename 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\test\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
3377 error      errno: -4048,
3377 error      code: 'EPERM',
3377 error      syscall: 'rename',
3377 error      path: 'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
3377 error      dest: 'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate' },
3377 error   stack: 'Error: EPERM: operation not permitted, rename \'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate\' -> \'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate\'',
3377 error   errno: -4048,
3377 error   code: 'EPERM',
3377 error   syscall: 'rename',
3377 error   path: 'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
3377 error   dest: 'C:\\Users\\test\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate',
3377 error   parent: 'npm' }
3378 error Please try running this command again as root/Administrator.
3379 verbose exit [ -4048, true ]

**Comment by dmitry-shibanov** [comment] 2022-01-31 09:36
Hello everyone. Thank you for your report. I think it should be related to this [issue](https://github.com/npm/cli/issues/4341). As a workaround for now you can specify npm version as `8.3.1`.
```
      - name: Install latest npm version
        run: npm install --global npm@8.3.1
```

**Comment by willemmulder** [comment] 2022-02-03 21:20
I have the same problem, and fixing the version to 8.3.1 worked for me.

**Comment by milleniait** [comment] 2022-02-06 23:10
Join the All New Cross chain project Dogelana $DGLN.

Doge and Solana introduces the best and fastest Network on Blockchain.
Join us to partake in our IEO/ICO/NFT GIVEAWAY

https://t.me/+ZtYF6PzehrMxYmE0

**Comment by michael-strother-wth** [comment] 2022-02-07 15:40
I ran into the same issue... installing 8.3.1 as a workaround worked for me.

**Comment by DahirWarsame** [comment] 2022-02-09 13:51
I had the same issue.  After running the `npm install -g npm@latest` command I got the same error.
```
C:/WINDOWS/system32 via 🦀
❯ npm install -g npm@latest
npm WARN npm npm does not support Node.js v14.15.1
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 6, 8, 9, 10, 11, 12.
npm WARN npm You can find the latest version at https://nodejs.org/
npm ERR! path C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate
npm ERR! code EPERM
npm ERR! errno -4048
npm ERR! syscall rename
npm ERR! Error: EPERM: operation not permitted, rename 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'
npm ERR!  [OperationalError: EPERM: operation not permitted, rename 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!   cause: [Error: EPERM: operation not permitted, rename 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\.node-gyp.DELETE\node_modules\@tootallnate' -> 'C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\node_modules\@tootallnate'] {
npm ERR!     errno: -4048,
npm ERR!     code: 'EPERM',
npm ERR!     syscall: 'rename',
npm ERR!     path: 'C:\\Users\\<userName>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!     dest: 'C:\\Users\\<userName>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate'
npm ERR!   },
npm ERR!   errno: -4048,
npm ERR!   code: 'EPERM',
npm ERR!   syscall: 'rename',
npm ERR!   path: 'C:\\Users\\<userName>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\.node-gyp.DELETE\\node_modules\\@tootallnate',
npm ERR!   dest: 'C:\\Users\\<userName>\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\node_modules\\@tootallnate',
npm ERR!   parent: 'npm'
npm ERR! }
npm ERR!
npm ERR! The operation was rejected by your operating system.
npm ERR! It's possible that the file was already in use (by a text editor or antivirus),
npm ERR! or that you lack permissions to access it.
npm ERR!
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator (though this is not recommended).

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\<userName>\AppData\Roaming\npm-cache\_logs\2022-02-09T13_40_57_362Z-debug.log
The batch file cannot be found.
```

But installing v8.3.1 worked like charm 😁
```
C:/WINDOWS/system32 via 🦀 took 8s
❯ npm install --global npm@8.3.1
C:\Users\<userName>\AppData\Roaming\npm\npm -> C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
C:\Users\<userName>\AppData\Roaming\npm\npx -> C:\Users\<userName>\AppData\Roaming\npm\node_modules\npm\bin\npx-cli.js
+ npm@8.3.1
added 33 packages from 20 contributors and updated 181 packages in 7.559s

C:/WINDOWS/system32 via 🦀 took 8s
❯ npm -v
8.3.1

```

**Comment by Badisi** [comment] 2022-02-25 18:16
Installing `npm@8.3.1` before attempting to update npm to `latest` as worked for me.

```js
npm install -g npm@8.3.1
npm install -g npm@latest
```

**Comment by dmitry-shibanov** [comment] 2022-04-01 07:48
Hello everyone. I'm going to close the issue, because for now it works as expected. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-04-01 07:48 UTC
Labels: bug

**Comment by mmomtchev** [comment] 2022-11-10 20:01
@dmitry-shibanov this one seems back since today, it is 100% reproducible on Windows with Node.js 14.x: https://github.com/mmomtchev/pymport/actions/runs/3436129129/jobs/5737940944

**Comment by peterjuras** [comment] 2022-11-14 05:10
Opened #623 as a follow up. The issue is also happening again for me.

**Comment by Bekarysalashybayev** [comment] 2023-02-22 15:39
npm install -g npm@9.5.0
worked for me (with special version)
