### ISSUE TITLE
Nodejs binary is not cached

### ISSUE THREAD

**Issue by mpsq** [actions/setup-node#557] opened 2022-08-15 17:33 UTC
**Description:**
The nodejs binary is not cached, `setup-node` downloads it from `https://github.com/actions/node-versions/releases` on every run.

**Action version:**
Latest

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node 16.15.1

**Repro steps:**  
```
    - name: "Set up nodejs"
      uses: actions/setup-node@v3
      with:
        node-version-file: '.nvmrc'
```

In a composite action.

**Expected behavior:**
Nodejs binary should be pulled from the cache, not downloaded every time.

**Actual behavior:**
Logs showing the issue:

```
Resolved .nvmrc as 16.15.1
Attempting to download 16.15.1...
Acquiring 16.15.1 - x64 from https://github.com/actions/node-versions/releases/download/16.15.1-2426430333/node-16.15.1-linux-x64.tar.gz
Extracting ...
/usr/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/runner/work/_temp/fa1f695b-6acd-4867-b040-2ef9482f9b49 -f /home/runner/work/_temp/1f3d7c09-4341-4773-9225-73d14d319922
Adding to the cache ...
Done
```

In the logs above we see "Adding to the cache ...", but on a subsequent run the same happens (.i.e. nodejs is downloaded from `node-versions/releases`). This means that a subsequent runs also shows "Attempting to download 16.15.1..." although the binary should come from the cache this time.

I also tried to set the nodejs version directly (without a file), same issue.

**Comment by dmitry-shibanov** [comment] 2022-08-15 18:28
Hello @mpsq. Thank you for your report. I think it is an expected behaviour because the runners get cleaned after end of the job that is why it download Nodejs. Could you please share the link of the build ?

**Comment by mpsq** [comment] 2022-08-15 19:32
Ha, I see, I was expecting the cache to behave like `actions/cache` does (with a key based on the `arch` and node version). Do you know if there is a way I could add this logic?
The use-case makes sense for a workflow that uses many (~8-10) small jobs.

**Comment by jpike88** [comment] 2022-08-22 07:28
"because the runners get cleaned after end of the job that is why it download Nodejs"

But this action is supposed to do caching right? It's already caching the node_modules folder etc, so why wouldn't you also cache Nodejs, and do a check next time to see if it's already in cache or not instead of downloading every time??

**Comment by dmitry-shibanov** [comment] 2022-08-22 08:12
Hello everyone. Hosted images have preinstalled [versions](https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md#cached-tools) of Nodejs in hosted toolcache directory, the action can utilize them. According to [documentation](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) the action caches global package dependencies. The action does not cache `node_modules`. 

When the job is finished the hosted runners get cleaned to the initial state that is why the Nodejs will be installing for next jobs. 

For now I'm going to close the issue because it's an expected behaviour.

**Closed by dmitry-shibanov** 2022-08-22 08:12 UTC
Labels: bug

**Comment by jpike88** [comment] 2022-08-22 08:56
Sorry I switched tabs and read the wrong repo name! Ignore my last message.

I think there should be a simple improvement that checks `downloadPath` to see if there's already a matching binary there, that way we can use other caching actions to leverage this. Should be simple enough right

**Comment by jpike88** [comment] 2022-08-22 09:15
oops ignore
