### ISSUE TITLE
Cache issue in pnpm 7

### ISSUE THREAD

**Issue by riderx** [actions/setup-node#597] opened 2022-10-18 08:18 UTC
**Description:**
Cache is not used in the action as expected. 0 package are reused by pnpm.
```
Run pnpm install --frozen-lockfile
Lockfile is up to date, resolution step is skipped
Progress: resolved 1, reused 0, downloaded 0, added 0
Packages: +22[8](https://github.com/Cap-go/capgo/actions/runs/3262889396/jobs/5360721055#step:5:9)2
```

**Action version:**
actions/setup-node@v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
Nodejs 16
pnpm 7

**Repro steps:**  
This is the public action who fail, you can find the code in the second link
https://github.com/Cap-go/capgo/actions/runs/3262889396/jobs/5360721055
https://github.com/Cap-go/capgo/actions/runs/3262889396/workflow

**Expected behavior:**
cache should make pnpm reuse package between run of the same job.
The goal is to reduce build time and action usage by keeping cache of plugin between job ( who happen in every commit)

**Actual behavior:**
not reused

Linked to https://github.com/actions/setup-node/issues/479

**Comment by marko-zivic-93** [comment] 2022-10-18 08:31
Hello @riderx,
Thank you for creating this issue. We will investigate it and come back to you as soon as we have some information related to it :)

**Comment by riderx** [comment] 2022-10-19 12:10
i had already the issue with only one job. i don't think that the issue

**Comment by riderx** [comment] 2022-10-19 12:31
https://github.com/Cap-go/capgo/actions/runs/3147474631/jobs/5117013958

**Comment by dmitry-shibanov** [comment] 2022-10-19 13:10
Could you please rerun this job ?

**Comment by riderx** [comment] 2022-10-19 13:50
i did remove the parallel jobs to make like it was again, since they always fail anyway https://github.com/Cap-go/capgo/actions/runs/3282130125/jobs/5405104107

**Comment by dmitry-shibanov** [comment] 2022-10-23 12:34
Hello @riderx. It can be so because it runs on the different branch than the default one that is why it resaves cache. It can be related to this [issue](https://github.com/actions/setup-node/issues/539).

**Comment by riderx** [comment] 2022-10-23 14:25
good catch that definitely sound like my problem.
pnpm has a global cache for all in local, so it should behave the same in ci for me.
do you think we can make something like that ?

**Comment by dmitry-shibanov** [comment] 2022-10-23 20:10
I've tried to reproduce the issue and I think it can be limitation with branching. I've run it on the tag 1.35.2 and for the first run the action saved cache and for the second it could restore cache, that is why I think it's [cache limits](https://github.com/actions/cache#cache-limits).

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-10-23 20:10 UTC
Labels: bug

**Comment by riderx** [comment] 2022-10-27 07:29
hey @dmitry-shibanov thank you so much for your insights, I was able to resolve my issue by adding a cache step on the main branch before the CI on tag just here : 
https://github.com/Cap-go/capgo/blob/36b3f36d1d42954534ac98116f4a1ab6f0da4a41/.github/workflows/bump_version.yml#L36
It's not ideal, since building each tag seems logical without building the main, but that have reduce my install time from 2 min to 9 sec ^^
