### ISSUE TITLE
Installing not the latest Node 18.13

### ISSUE THREAD

**Issue by shyim** [actions/setup-node#661] opened 2023-01-09 13:16 UTC
**Description:**

I have in my yaml
```
      - uses: actions/setup-node@v3
        with:
          node-version: 18
```

and expect it installs always the latest 18 version, but In the CI I have `v18.12.1` the latest one is `18.13.0`

**Action version:**
Specify the action version

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
```
  node: v18.12.1
  npm: 8.19.2
  yarn: 1.22.19
```

**Repro steps:**  
https://github.com/shopware/platform/actions/runs/3873523857/jobs/6603640318#step:9:1544

**Expected behavior:**
The latest Node 18 version

**Actual behavior:**
Got v18.12.1

**Comment by dmitry-shibanov** [comment] 2023-01-09 14:29
Hello @shyim. Thank you for your report. It's an expected behaviour because initially action tries to set up the version from the hosted toolcache directory. Could you please try to set check-latest: true to get the latest version. 
```yaml
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        check-latest: true
```
For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-01-09 14:29 UTC
Labels: bug

**Comment by Hongbo-Miao** [comment] 2023-02-03 14:16
Hi @dmitry-shibanov I got same error, the latest one is 18.14.0 now, however even I add `check-latest: true`, it still does not work. I opened a new ticket at https://github.com/actions/setup-node/issues/689 Thanks! 😃
