### ISSUE TITLE
can't get `yarn` cache to restore effectively

### ISSUE THREAD

**Issue by dkoston** [actions/setup-node#834] opened 2023-08-21 21:07 UTC
**Description:**

We upgraded to v3 recently and started using `cache: "yarn"` but when we use another step and try to run yarn after restoring the cache, we get:

```
Run yarn lint
Usage Error: Couldn't find the node_modules state file - running an install might help (findPackageLocation)

$ yarn run [--inspect] [--inspect-brk] [-T,--top-level] [-B,--binaries-only] <scriptName> ...
Error: Process completed with exit code 1.
```
Could not find other reports of this happening.

**Action version:**
v3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**

```
Run actions/setup-node@v3
Found in cache @ /opt/hostedtoolcache/node/16.20.2/x64
Environment details
/usr/local/bin/yarn --version
3.2.1
```

**Repro steps:**  

Use this .github/workflows/ci.yml config:

```

name: CI

# Controls when the action will run.
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

  workflow_dispatch:

env:
  NODE_VERSION: '16'

jobs:
  # Setup environment
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Install Dependencies
        run: yarn --immutable

  # Run linting and typechecks
  check:
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'yarn'

      - name: Check Code Format
        run: |
          yarn lint
          yarn prettier:check

      - name: Check Typescript
        run: |
          yarn tsc
```

**Expected behavior:**
Yarn modules and files would be cached and `yarn lint` would just run

**Actual behavior:**
Yarn can't find files so it thinks we need to run `yarn install`

**Comment by iCrawl** [comment] 2023-08-21 22:35
Once upon a time a time I discovered this great composite action for yarn2/3/4:

https://github.com/discordjs/discord.js/commit/c0e3629f64042c7363f9dae6830bc2f6a7e5c7d4

I'm not exactly sure where I got it from anymore, but it works wonders and keeps yarn install times low, as they should be.
Obviously this isn't a solution for the issue at hand (it not working properly in this action, but hey better than nothing!)

**Comment by dusan-trickovic** [comment] 2023-08-22 07:31
Hello, @dkoston ! Thank you for filing this issue. We will take a closer look into it and see what can be done :)

**Comment by maks-rafalko** [comment] 2023-09-04 10:23
@dkoston were you able to make it working? Cache doesn't work for us as well for `yarn`

**Comment by dkoston** [comment] 2023-09-04 14:29
@maks-rafalko we haven't been able to get it working. Been using this as a workaround:

```
      - uses: actions/cache@v3
        id: restore-deps
        with:
          path: ./*
          key: ${{ github.sha }}-deps
```

**Comment by fryderykkruczek** [comment] 2023-09-13 12:39
In my case, I forgot that the node_modules folder is not cached by default with ```cache: "yarn"```.
So I had to cache it additionally - that fixed the problem.

**Comment by maks-rafalko** [comment] 2023-09-13 12:49
would you mind share the code to additionally cache `node_modules`?

**Comment by fryderykkruczek** [comment] 2023-09-13 13:37
Everywhere where you need node_modules for example:
```
    - uses: actions/cache@v3
      with:
        key: node_modules-${{ runner.os }}-${{ hashFiles('path-to/yarn.lock') }}
        path: path-to/node_modules
```

**Comment by dsame** [comment] 2023-11-30 10:54
Hello @dkoston, I noticed that you are using Yarn 3, which is not supposed to have node_modules. Also, yarn config get cacheFolder does not return it if your build is configured to use [pnp](https://yarnpkg.com/features/pnp) instead of node_modules.

Could you please provide the logs of the build experiencing the issue? If possible, include the Yarn configuration to help identify the reason why the CLI does not report node_modules but requires it in the next step.

**Comment by dsame** [comment] 2023-12-25 08:12
Hello @dkoston , the issue is not active more than 2 weeks, i am closing it, but please feel free to reopen it or create the new one in case if the problem still exists.

**Closed by dsame** 2023-12-25 08:12 UTC
Labels: bug
