### ISSUE TITLE
setup-node is overwriting my .npmrc that I'm setting via docker secrets.

### ISSUE THREAD

**Issue by wallentx** [actions/setup-node#242] opened 2021-03-16 19:12 UTC
I just need setup-node to not try and do certain things, like all of the stuff with .npmrc that it does without any request or input from me. If I set flags for the registry, or the scope, then sure, it should go ahead and try and set those. But I'm running a self-hosted runner and I've already standardized a build workflow that utilizes best practices so that devs don't have to interface with secrets via repo settings and the workflow yaml.

I'm injecting .npmrc on my own, but setup-node blanks it out.

**Comment by dmitry-shibanov** [comment] 2021-11-11 12:40
Hello @wallentx, just a gentle ping.

**Comment by dmitry-shibanov** [comment] 2021-11-15 10:39
Hello @wallentx . I'm going to close the issue, because we can not reproduce it from our side. Please provide us with steps to reproduce the issue for further investigation.

**Closed by dmitry-shibanov** 2021-11-15 10:39 UTC
Labels: bug
