### ISSUE TITLE
Intermittent timeouts in `actions/setup-node@v3`

### ISSUE THREAD

**Issue by bennettp123** [actions/setup-node#733] opened 2023-03-30 08:58 UTC
**Description:**

**Action version:**
`'actions/setup-node@v3' (SHA:64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c)`

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [ ] Windows
- [x] Linux

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Tools version:**
```
  node: v14.21.3
  npm: 6.14.18
  yarn: 1.19.1
```

**Repro steps:**  

Intermittently, the setup-node action times out after 60 minutes. Logs indicate that it's restoring yarn cache. 

**Expected behavior:**

EITHER
* restore cache succeeds quickly
OR
* setup-node times out after a minute or two, proceeds without cache

**Actual behavior:**

* restore cache stalls, and the workflow eventually times out

**Comment by bennettp123** [comment] 2023-03-30 09:04
I initially suspected actions/setup-node needed updating to use the [default 10-minute segment timeout](https://github.com/actions/cache/blob/main/tips-and-workarounds.md#cache-segment-restore-timeout).

Upon closer inspection, actions/setup-node [uses a version of actions/cache](https://github.com/actions/setup-node/blob/a4fcaaf314b117a40d694a35ee36461f8ff3c6e6/package-lock.json#L41) with a [default timeout of 60 minutes](https://github.com/actions/toolkit/blob/457303960f03375db6f033e214b9f90d79c3fe5c/packages/cache/RELEASES.md#304) (not 10 minutes, as indicated by `actions/cache`, above).

**Comment by MaksimZhukov** [comment] 2023-03-30 09:24
Hello @bennettp123!
Thank you for reporting this! We will investigate the issue

**Comment by statico** [comment] 2023-04-18 17:15
We're also experiencing this issue. Disabling the yarn cache fixed our builds temporarily but we'll try this.

**Comment by millsp** [comment] 2023-04-19 19:11
Same here, we encounter this frequently https://github.com/prisma/prisma/actions/runs/4746282641/jobs/8429723075#step:9:438

**Comment by mahabaleshwars** [comment] 2024-11-22 07:47
Hello @bennettp123, 

The default timeout has been reduced to 10 minutes. Could you please verify on your end if this resolves the issue? If not, kindly provide the reproduction steps. For reference, you can review the changes made in the [options.ts](https://github.com/actions/toolkit/blob/main/packages/cache/src/options.ts#L106-L113) file

**Comment by mahabaleshwars** [comment] 2024-12-04 03:15
Hello @bennettp123,

Just a quick reminder to check if the issue has been resolved. Please let me know if there's anything else I can assist with!

**Comment by mahabaleshwars** [comment] 2024-12-11 03:20
Hello @bennettp123, We will be closing this issue for the time being due to lack of recent communication. However, please don't hesitate to reach out if you have any further questions or concerns, and we’ll be happy to reopen the issue as needed.

**Closed by mahabaleshwars** 2024-12-11 03:20 UTC
Labels: bug
