### ISSUE TITLE
Can't mange to use Volta

### ISSUE THREAD

**Issue by javier-tarazaga** [actions/setup-node#687] opened 2023-02-01 09:48 UTC
**Description:**
I saw that in one of the lates release, the support for Volta was introduced. We have added Volta to our `package.json` file but when the action is running, I don't see the version we specify in the Volta section being used. 

**Action version:**
Latest v3.

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**  
Simply add this at the end of your `package.json`:

```
"volta": {
    "node": "18.13.0"
  }
```

**Expected behavior:**
The action would be picking Volta's node version and use that. 

**Actual behavior:**
The action is actually showing us this: 

```
Run actions/setup-node@v3
  with:
    cache: npm
    always-auth: false
    check-latest: false
    token: ***
Environment details
  node: v16.19.0
  npm: 8.19.3
  yarn: 1.2
```

**Comment by MaksimZhukov** [comment] 2023-02-01 10:31
Hello @javier-tarazaga !
I could not reproduce your issue, everything works as expected. Could you please provide us with a public repository where the issue occurs?

**Comment by MaksimZhukov** [comment] 2023-02-06 11:37
I am closing the issue. 
To fix the issue, please use the `node-version-file` input, as mentioned in the [documentation](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file).
Feel free to contact us if you have any questions.

**Closed by MaksimZhukov** 2023-02-06 11:37 UTC
Labels: bug
