### ISSUE TITLE
npm: command not found (on windows-latest)

### ISSUE THREAD

**Issue by pinheadmz** [actions/setup-node#596] opened 2022-10-17 21:56 UTC
Error message is here in this log: https://github.com/handshake-org/hnsd/actions/runs/3268540229/jobs/5375062932#step:8:8

Workflow file is here: https://github.com/handshake-org/hnsd/blob/0c0795c911b78d927b8d9c253220e9c4c5666a99/.github/workflows/test-windows.yaml

in this pull request: https://github.com/handshake-org/hnsd/pull/101

Everything works on Ubuntu and OSX in this workflow file: https://github.com/handshake-org/hnsd/blob/0c0795c911b78d927b8d9c253220e9c4c5666a99/.github/workflows/test.yml

Complete error:

```

> Run actions/setup-node@v3.5.1
  with:
    node-version: 16
    always-auth: false
    check-latest: false
    token: ***
  env:
    MSYSTEM: MINGW64
Found in cache @ C:\hostedtoolcache\windows\node\16.17.1\x64
Environment details
  node: v16.17.1
  
  yarn: 1.22.19
  
  npm: 8.15.0
  
  
0s


> Run npm install
D:\a\_temp\319090c3-3b53-435f-a807-966fa0e61c22: line 1: npm: command not found
Error: Process completed with exit code 127.

```

workflow file:

```
name: Test - Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}

    steps:
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git mingw-w64-x86_64-toolchain base-devel mingw-w64-x86_64-unbound autotools

      - run: git config --global core.autocrlf input
        shell: bash

      - uses: actions/checkout@v2

      - name: Build
        run: ./autogen.sh && ./configure --with-network=regtest && make

      - name: Unit Tests
        run: ./test_hnsd

      - name: Setup Integration
        uses: actions/setup-node@v3.5.1
        with:
          node-version: 16

      - name: Integration Tests
        working-directory: ./integration
        run:  |
              npm install
              npm run test

```

**Comment by dmitry-shibanov** [comment] 2022-10-18 10:48
Hello @philip-gai. The issue is related to `msys` because it cuts the PATH (`/mingw64/bin:/usr/local/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl`) that is why `npm` can't be found. You can take a look at logs from setup-node. The action calls `npm -v ` and it works as expected. I've tried to change shell for `Integration Tests` and it could find `npm`. 

For now I'm going to close the issue because the root cause comes from `msys`.

**Closed by dmitry-shibanov** 2022-10-18 10:48 UTC
Labels: bug

**Comment by pinheadmz** [comment] 2022-10-18 11:08
@dmitry-shibanov thank you! So... what did you change shell to exactly ...?

**Comment by dmitry-shibanov** [comment] 2022-10-18 11:22
@pinheadmz, I've changed shell to `pwsh` and it could find `npm`.

**Comment by pinheadmz** [comment] 2022-10-19 13:37
@dmitry-shibanov ok thanks, that got npm running on CI, but now my issue is that I am using npm to test code compiled in msys2. So there's something about the search PATH that isn't working cross-shell (I suppose). After setup-node is executed, where are node and npm executables located? I'll try to add that to my PATH in msys2.

**Comment by pinheadmz** [comment] 2022-10-19 14:30
SOLVED! If you are using msys2 you need to specify "inherit" path -- this will combine search PATHs from powershell (where setup-node installs npm) and msys2 (where my project needs to run npm from)

```
      - uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
```
