### ISSUE TITLE
Unnecessarily uses two API calls if a pre-cached version is not requested

### ISSUE THREAD

**Issue by anomiex** [actions/setup-node#446] opened 2022-03-21 14:25 UTC
**Description:**
If the version of node requested is not one of the versions pre-cached on the Actions job runners, this action will make two API calls to effectively do the same thing as downloading https://raw.githubusercontent.com/actions/node-versions/main/versions-manifest.json. Downloading that URL directly would use 0 API calls.

These API calls are counted against the API rate limits. In one small sampling in our repo while investigating "API rate limit exceeded" errors (data in GitHub support ticket 1513647), these calls represented 567 of the 958 hits (almost 60%) leading up to the event.

While the actual code involved [appears to be in your actions/toolkit repo](https://github.com/actions/toolkit/blob/d1abf7dc74ea38ed6c5552491cdf8b695b813722/packages/tool-cache/src/tool-cache.ts#L589-L632) rather than this one. GitHub Support asked me to raise this here.

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

Node version 16.13.2, being installed by this action. Pnpm version 6.23.6.

**Repro steps:**  
You can see it easily enough in [this](https://github.com/anomiex/testing/runs/5588626742?check_suite_focus=true) test run on my personal repo, which used [this](https://github.com/anomiex/testing/blob/cd4c7a50dbefa672330f19bace596b95a5630b06/.github/workflows/test.yml#L15-L47) workflow.

**Expected behavior:**
API rate limit is not unnecessarily used.

**Actual behavior:**
* [Here](https://github.com/anomiex/testing/runs/5588626742?check_suite_focus=true#step:4:74), before running this action, we see the rate limit usage was 2/1000.
* After using the action to install a cached version of node, [here](https://github.com/anomiex/testing/runs/5588626742?check_suite_focus=true#step:6:74) we see the usage was still 2/1000.
* After using the action to install an uncached version of node, [here](https://github.com/anomiex/testing/runs/5588626742?check_suite_focus=true#step:8:75) we see the usage has gone up to 4/1000.

**Comment by dmitry-shibanov** [comment] 2022-03-28 08:47
Hello @anomiex. Thank you for your report. We'll investigate the issue.

**Comment by marko-zivic-93** [comment] 2022-04-04 12:11
Hello @anomiex ,

After the investigation we came to the conclusion that this is not an issue on our side, since these "additional calls" are probably happening when manifest is being fetched, and the second one is happening when toolkits downloadTool gets invoked, so in a way this is expected behaviour. 

That is why I will close this issue now. If you have any questions or concerns, please feel free to leave a comment on this thread or open another issue

**Closed by marko-zivic-93** 2022-04-04 12:11 UTC
Labels: bug

**Comment by anomiex** [comment] 2022-04-05 21:49
Your (GitHub's) own support is who asked me to open this here. If you agree it's in one of your (GitHub's) other repositories, why not copy it there instead of just closing this with "not my problem"?
