### ISSUE TITLE
Action succeds for push but fails for pull_request

### ISSUE THREAD

**Issue by TheRealSyler** [actions/setup-node#774] opened 2023-06-09 19:23 UTC
**Description:**
Im trying to use private npm packages which works if the `event_name` is `push` but fails for `pull_request`

**Action version:** @v3

**Platform:**
- [x] Ubuntu

**Runner type:**
- [x] Hosted

**Tools version:**

* node 16
* yarn v1.22.19

**Repro steps:**
1. create private npm package in a different repository
2. install npm package and run the workflow below
3. create pull request to trigger `pull_request` event

```yml
on: [push, pull_request]

permissions:
  checks: write
  contents: write
  packages: read

jobs:
  eslint:
    name: EsLint
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
          registry-url: "https://npm.pkg.github.com"

      - name: Install Packages
        run: yarn install --frozen-lockfile
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
      - name: Run Eslint
        run: yarn lint
```

**Expected behavior:**
the workflow should succeed for `push` and `pull_request`

**Actual behavior:**
the workflow succeeds for `push` but NOT for `pull_request`
![awd](https://github.com/actions/setup-node/assets/46901787/ec190fac-aaf6-49e9-8089-54f25a67d92e)

here is the output of the failed action (edited to remove repo/package/org name)
```sh
Run yarn install --frozen-lockfile
yarn install v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
error An unexpected error occurred: "https://npm.pkg.github.com/download/@ORG/PACKAGE/0.1.1/fba695989c735ad45d4096f225870da3c3faf5cc: Request failed \"403 Forbidden\"".
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/REPO/REPO/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Error: Process completed with exit code 1.
```

**Comment by dusan-trickovic** [comment] 2023-06-09 20:58
Hello, @TheRealSyler ! Thank you for creating the issue, we will take a look and get back to you with the answer :)

**Comment by dmitry-shibanov** [comment] 2023-07-18 13:43
Hello @TheRealSyler. Sorry for the late response. It looks like the issue with permissions for token that is why I think that the root cause not in setup-node. I could resolve it by [adding repository in packages](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#github-actions-access-for-packages-scoped-to-personal-accounts) settings and changing permission package to write. Could you please also check this [link](https://docs.github.com/en/packages/learn-github-packages/configuring-a-packages-access-control-and-visibility#ensuring-workflow-access-to-your-package).

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-07-18 13:43 UTC
Labels: bug
