### ISSUE TITLE
Cannot install node 18.12.1

### ISSUE THREAD

**Issue by Andrurodr** [actions/setup-node#631] opened 2022-11-23 17:26 UTC
**Description:**
I can't setup node version 18.12.1, seems like the installation was failed.

Attempting to download 18.12.1...
Acquiring 18.12.1 - x64 from https://github.com/actions/node-versions/releases/download/18.12.1-3486235546/node-18.12.1-linux-x64.tar.gz
Received HTTP status code 403.  This usually indicates the rate limit has been exceeded
Falling back to download directly from Node
Acquiring 18.12.1 - x64 from https://nodejs.org/dist/v18.12.1/node-v18.12.1-linux-x64.tar.gz
Extracting ...
/bin/tar xz --strip 1 --warning=no-unknown-keyword -C /home/<user>/ghub-runner-02-1/_work/_temp/feda96cb-2999-4572-97c8-82edc9eae7d5 -f /home/<user>/ghub-runner-02-1/_work/_temp/1b12f401-bf01-4e4c-aea0-ddab8ea827b8
Adding to the cache ...
Done
Environment details:
  Warning: /home/<user>/ghub-runner-02-1/_work/_tool/node/18.12.1/x64/bin/node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by /home/<user>/ghub-runner-02-1/_work/_tool/node/18.12.1/x64/bin/node)
  
  node: 
  Warning: node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28` not found (required by node)
  
  npm: 
  Warning: node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28` not found (required by node)
  
 And then when I tried to use it
 
 Run: npm config set proxy $CONDUCTOR_PROXY_FULL
node: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by node)

**Action version:**
V 3.5.1

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [X] Self-hosted

**Tools version:**
npm: 8.19.2

**Repro steps:**  
- name: "Setup Node"
        uses: actions/setup-node@v3.5.1
        with:
          node-version: '18.12.1'
- name: "Install dependencies"
  run: |
    npm install

**Expected behavior:**
Node with version 18.12.1 installed and working

**Actual behavior:**
Cannot execute any command, the error occurs.

**Comment by dmitry-shibanov** [comment] 2022-11-23 17:30
Hello @Andrurodr. Thank you for your report. Which version of ubuntu do you use ?

**Comment by Andrurodr** [comment] 2022-11-23 17:33
Hello ! I'm using Ubuntu 18.04.5

**Comment by dmitry-shibanov** [comment] 2022-11-23 17:37
I think it is an expected behaviour. We have similar issue related to this https://github.com/actions/setup-node/issues/507. Node 18 is compatible with Linux distributions based on GLIBC 2.28 or later but Ubuntu 18.04 uses older one. 

For now I'm going to close the issue because the issue comes from the system.

**Closed by dmitry-shibanov** 2022-11-23 17:37 UTC
Labels: bug

**Comment by francois-codes** [comment] 2023-04-08 09:41
@dmitry-shibanov I'm facing this issue as well trying to build a self hosted runner on ubuntu 22.04. using actions/setup-node@v3 to install node 18 yields the same glibc error here, even though the image is supposed to have a higher version glibc (2.35 I believe)

**Comment by dmitry-shibanov** [comment] 2023-04-10 08:28
Hello @francois-codes. I've tried to reproduce the issue but everything works as expected. I think it is an issue with your set up of image.

**Comment by francois-codes** [comment] 2023-04-10 08:54
@dmitry-shibanov yes, thank you, I found the problem was that while I was pushing new images, github was still trying to use older outdated images. It works fine and the issue I had was not related to this repo
