### ISSUE TITLE
v2.5.0 breaks existing builds installing newer versions of nodejs

### ISSUE THREAD

**Issue by cesarizu** [actions/setup-node#375] opened 2021-12-02 17:42 UTC
**Description:**
With v2.5.0 existing repos that specify a node version on `package.json` and/or `.nvmrc` but do not use `node-version-file` will start using newer versions of nodejs than the requested.

**Action version:**
v2.5.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
Nodejs v14

**Repro steps:**  
Create a repo with a `.github/workflows/test.yml` that includes:

```
    - name: Set up Node.js
      uses: actions/setup-node@v2
```

And set `package.json` to use:

```
  "engines": {
    "node": "14.x"
  }
```

And `.nvmrc` to use:

```
v14
```

**Expected behavior:**
Version 14 is installed

**Actual behavior:**
Version 16 is installed

**Comment by dmitry-shibanov** [comment] 2021-12-03 08:16
Hello @cesarizu. Thank you for your report. Changes in 2.5.0 release are not related to the issue. If no `input node-version` or `node-version-file` is specified, the default Nodejs version from the image will be used. [Hosted images](https://github.com/actions/virtual-environments/issues/4446) updated default Nodejs version to 16.
For now I'm closing the issue, because it's an expected behaviour. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-12-03 08:16 UTC
Labels: bug
