### ISSUE TITLE
Getting error while executing '-run: npm ci'

### ISSUE THREAD

**Issue by subinsuresh** [actions/setup-node#498] opened 2022-05-25 11:07 UTC
I am developing flutter app, when i tried to upload android apk to the firebase distribution. I need to set the node version explicitly, so I have added below line to mention the node version in yaml file like this

    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 16.3.0

    - run: npm ci
    - run: npm test

I am getting an error like this,  Since its an flutter project it doesnt contains any json files(like package-lock.json)
npm ERR! The `npm ci` command can only install with an existing package-lock.json or
npm ERR! npm-shrinkwrap.json with lockfileVersion >= 1. Run an install with npm@5 or
npm ERR! later to generate a package-lock.json file, then try again.

**Comment by dmitry-shibanov** [comment] 2022-05-25 11:30
Hello @subinsuresh. Thank you for your report. I think it's an expected behaviour because for the `npm ci `command you need to provide the package-lock.json.
For now I'm going to close the issue because it is not related to setup-node itself. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-05-25 11:30 UTC
Labels: bug
