### ISSUE TITLE
What is default `registry-url`?

### ISSUE THREAD

**Issue by jasonkarns** [actions/setup-node#82] opened 2019-11-05 00:29 UTC
The action.yml documents `registry-url` as optional but doesn't specify what the default is. Is it npm or github?

More interestingly... will this action properly respect [`publishConfig`](https://docs.npm.red/files/package.json#publishconfig) from package.json? Typically, `tag` and `registry` and `access` are things that should be configured at the _project_ level and so they should be configured in the package.json, not `.npmrc` (which is a user-specific file). If the registry is specified this way (`package.json#publishConfig.registry`), will that be used properly when the workflow omits the registry param?

**Comment by Andarist** [comment] 2021-09-11 21:08
> The action.yml documents registry-url as optional but doesn't specify what the default is. Is it npm or github?

I believe that the default is the default of `npm` - which would be `//registry.npmjs.org/`. 

> More interestingly... will this action properly respect publishConfig from package.json? 

I believe this would take precedence over whatever this action sets. The main reason is that this action doesn't actually use this info - it just sets it up. So what ends up being used is really up to other things in your development chain. For instance, if you try to publish a package then, I believe, the npm would pick up `publishConfig` before falling back to `.npmrc` contents

**Comment by dmitry-shibanov** [comment] 2021-11-16 14:24
Hello @jasonkarns. Thank you for report. Sorry for the late response. If you do not specify the registry-url input, .npmrc file for authentication won't be generated. If the default registry for nodejs will be `https://registry.npmjs.org/` (`npm config get registry`). 

Speaking about publishConfig in package.json, .npmrc file has more priority than publshConfig in package.json, so it will override properties.

Thanks @Andarist for your answer.

**Comment by dmitry-shibanov** [comment] 2021-11-29 09:24
Hello everyone. For now I'm closing the issue. If you still have any questions feel free to contact us.

**Closed by dmitry-shibanov** 2021-11-29 09:24 UTC
Labels: question

**Comment by Andarist** [comment] 2021-11-29 10:18
> Speaking about publishConfig in package.json, .npmrc file has more priority than publshConfig in package.json, so it will override properties.

I don't think this is true - I've went to check this out in the npm's CLI. The `.npmrc` value is being received [here](https://github.com/npm/cli/blob/940ba878019e7b35bda20a26baaa4c99bebc906b/lib/commands/publish.js#L64) but is being overridden [here](https://github.com/npm/cli/blob/940ba878019e7b35bda20a26baaa4c99bebc906b/lib/commands/publish.js#L71-L73) (if the `publishConfig.registry` is set) and it's finally chosen [here](https://github.com/npm/cli/blob/940ba878019e7b35bda20a26baaa4c99bebc906b/lib/commands/publish.js#L105). Note that this is not just based on reading the source code. I'v double-checked this by hooking up a debugger and inspecting those values:
<img width="318" alt="Screenshot 2021-11-29 at 11 15 30" src="https://user-images.githubusercontent.com/9800850/143849797-8a3f163b-43d8-4ed3-844c-d635b9f3ff0c.png">

**Comment by dmitry-shibanov** [comment] 2021-12-02 09:29
Hello @Andarist. Thank you for your answer. I've tried to reproduce it from my side. I've created repository to publish to GPR. I've added https://registry.npmjs.org/ in publishConfig.registry and created .npmrc file through the setup-node action. Everything worked as expected. It means that the publish command picked up value from the .npmrc file.
According to the logs:
```
npm verb cli [
npm verb cli   '/opt/hostedtoolcache/node/16.13.0/x64/bin/node',
npm verb cli   '/opt/hostedtoolcache/node/16.13.0/x64/bin/npm',
npm verb cli   'publish',
npm verb cli   '--loglevel',
npm verb cli   'verbose'
npm verb cli ]
npm info using npm@8.1.0
npm info using node@v16.13.0
npm timing npm:load:whichnode Completed in 0ms
npm timing config:load:defaults Completed in 1ms
npm timing config:load:file:/opt/hostedtoolcache/node/16.13.0/x64/lib/node_modules/npm/npmrc Completed in 1ms
npm timing config:load:builtin Completed in 2ms
npm timing config:load:cli Completed in 1ms
npm timing config:load:env Completed in 1ms
npm timing config:load:file:/home/runner/work/testNpmPublish/testNpmPublish/.npmrc Completed in 0ms
npm timing config:load:project Completed in 1ms
npm timing config:load:file:/home/runner/work/_temp/.npmrc Completed in 1ms
npm timing config:load:user Completed in 1ms
npm timing config:load:file:/opt/hostedtoolcache/node/16.13.0/x64/etc/npmrc Completed in 1ms
npm timing config:load:global Completed in 1ms
```

**Comment by Andarist** [comment] 2021-12-02 09:45
Hm, I don't see anything that interesting in this log - I mean, it says which `.npmrc` files it has loaded but it doesn't say much about which registry it has used for the publishing itself.

What had you put in your `.npmrc` through setup-node? The GPR URL? Where the package was published at the end?

**Comment by dmitry-shibanov** [comment] 2021-12-02 09:52
Hello @Andarist. I put the GPR URL in the `.npmrc` file and put the `npmjs` registry in `publishConfig.registry`.

**Comment by Andarist** [comment] 2021-12-02 10:12
And where the package was published at the end? to the GPR?

**Comment by dmitry-shibanov** [comment] 2021-12-02 10:15
The package was published to the GPR

**Comment by Andarist** [comment] 2021-12-02 11:07
Thank you for confirming - I guess I will have to dig into this deeper then, cause it doesn't match what I've seen in the debugger. This sounds especially weird to me since the `publishConfig` seems to me as something "closer" to the package - and as such, I think it should take a priority. This seems especially important in monorepos - where you might want to setup a default registry through some `.npmrc` file (at global/user/project level) but ąlso to have some of the packages to be published to another registry. 

I'm also not sure if npm has this concept - but at least in Yarn Berry you can have different fetch and publish registries, so in such a context this would make even more sense cause I assume that the registry put in the `.npmrc` is the "fetch" registry by default (that is being used as publish and audit registry as well if there are no special values for those). And the `publishConfig.registry` is definitely treated there as a publish registry and, if I understand correctly, this should take a priority there. So I would at least hope for consistent behavior between npm and Yarn Berry in this regard.

But dunno, this is becoming very confusing to me 🤷‍♂️ and I certainly don't assume that my line of thinking is correct - it's just surprising that you have observed different results than I did (although our testing methodology was different so there is a chance that I've not really looked through the whole execution path).

Just a last question - did you test this with a scoped package or a non-scoped one? Maybe this can cause some differences in behavior - IIRC I've been testing this with a scoped package.

**Comment by dmitry-shibanov** [comment] 2021-12-02 13:18
Hello @Andarist. I used scoped package name: `"@scope/package-name"` and my `.npmrc` file looked like this:
```
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
@dmitry-shibanov:registry=https://npm.pkg.github.com/
```
Besides, I think publishing logic depend from the scope of the registry. I've tried it one more time and used my `.npmrc` in the root of project with such content:
```
//npm.pkg.github.com/:_authToken=${NODE_AUTH_TOKEN}
registry=https://npm.pkg.github.com/
```
It took registry from the `publishConfig`. I think it depends also on the scope. If scope is not defined in `.npmrc` file, the publish command will take registry from `publishConfig`
