### ISSUE TITLE
version not node version

### ISSUE THREAD

**Issue by quinn** [actions/setup-node#111] opened 2020-02-06 22:13 UTC
it seems the option is called `version`, not `node-version`.

**Comment by sergioflores-j** [comment] 2020-02-10 14:46
Yes, that's right... This should be fixed, because every guide using this action uses `node-action`.

Reproduction:

If you don't change to `version` this is the output:
![image](https://user-images.githubusercontent.com/32045525/74159422-898f5280-4bfa-11ea-8e53-cf050f50c272.png)

After making the change from `node-version` to `version`:
![image](https://user-images.githubusercontent.com/32045525/74159584-c8bda380-4bfa-11ea-98f2-5912f849c26a.png)

**Comment by zachguo** [comment] 2020-02-13 19:53
No such issue with `@v1`. Probably it's introduced by `@v1.1.0`?

**Comment by peaceiris** [comment] 2020-03-02 03:37
See this definition in v1.1.0: https://github.com/actions/setup-node/blob/5273d0df9c603edc4284ac8402cf650b4f1f6686/action.yml#L5-L7

In v1.4.0:

https://github.com/actions/setup-node/blob/1c5c1375b3817ad821719597effe8e3d6f764930/action.yml#L8-L18

**Comment by bryanmacfarlane** [comment] 2020-03-12 03:08
version was deprecated.  node-version is the proper input.

**Closed** 2020-03-31 14:55 UTC
