### ISSUE TITLE
action download fails to extract archive file

### ISSUE THREAD

**Issue by markgoho** [actions/setup-node#544] opened 2022-07-12 19:58 UTC
**Description:**
The setup-node action cannot be downloaded

**Action version:**
v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
n/a

**Repro steps:**  
use the action in a workflow

**Expected behavior:**
the action downloads and is used

**Actual behavior:**
the action cannot be downloaded due to:
``` bash
Download action repository 'actions/setup-node@v3' (SHA:5b9[49](https://github.com/ideacrew/enroll/runs/7309204561?check_suite_focus=true#step:1:53)b50c3461bbcd5a540b150c368278160234a)
##[debug]Download 'https://api.github.com/repos/actions/setup-node/tarball/5b949b50c3461bbcd5a540b150c368278160234a' to '/home/runner/work/_actions/_temp_5db10cf7-c813-4a48-be47-45d74a09eaa7/77720dc4-ac1f-4e76-9010-ecf0b2b7adb2.tar.gz'
Error: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_5db10cf7-c813-4a48-be47-45d74a09eaa7/77720dc4-ac1f-4e76-9010-ecf0b2b7adb2.tar.gz. return code: 2.
##[debug]System.NotSupportedException: Can't use 'tar -xzf' extract archive file: /home/runner/work/_actions/_temp_5db10cf7-c813-4a48-be47-45d74a09eaa7/77720dc4-ac1f-4e76-9010-ecf0b2b7adb2.tar.gz. return code: 2.
```

here is a dump from a successful download action:
``` bash
Download action repository 'actions/checkout@v3' (SHA:25[41](https://github.com/ideacrew/enroll/runs/7309204561?check_suite_focus=true#step:1:45)b1294d2704b0964813337f33b291d3f8596b)
##[debug]Download 'https://api.github.com/repos/actions/checkout/tarball/2541b1294d2704b0964813337f33b291d3f8596b' to '/home/runner/work/_actions/_temp_8658b1a3-50c0-48d5-a019-faa131ff87a7/a304dd22-9a2a-4980-bd2d-4e2fd9524024.tar.gz'
##[debug]Unwrap 'actions-checkout-2541b12' to '/home/runner/work/_actions/actions/checkout/v3'
##[debug]Archive '/home/runner/work/_actions/_temp_8658b1a3-50c0-48d5-a019-faa131ff87a7/a304dd22-9a2a-4980-bd2d-4e2fd9524024.tar.gz' has been unzipped into '/home/runner/work/_actions/actions/checkout/v3'.
```

**Comment by djalmaaraujo** [comment] 2022-07-12 19:59
Having the same problem for `actions/setup-node@v3`. Blocking our repo from using the main branch.

**Comment by amhunt** [comment] 2022-07-12 20:02
Same here. Interestingly, it seems to work ~20% of the time (so we're rerunning CI jobs a bunch atm 😂)

**Comment by dudadornelles** [comment] 2022-07-12 20:11
Try using a different cache key or clearing the cache - things worked after I cleared the node cache entries we had but unclear if it was luck

**Comment by djalmaaraujo** [comment] 2022-07-12 20:13
Can confirm `actions/setup-node@v2` works on our case. I am not sure how to clear the cache. Should we remove the line that mention cache in the config and, after a successful build, add again? @dudadornelles

**Comment by dmitry-shibanov** [comment] 2022-07-12 20:16
Hello everyone. Thank you for your reports. I think it's GitHub internals issue because the same behaviour can be reproduced with some other [actions](https://github.com/actions/checkout/issues/673).

**Comment by dudadornelles** [comment] 2022-07-12 20:45
@djalmaaraujo afaik you can only delete using the api, this may be helpful https://gist.github.com/dudadornelles/eacf6f3a796a0b509fac9ef9a7da59b9

**Comment by ddzz** [comment] 2022-07-14 16:40
Was this fixed in `[3.4.0](https://github.com/actions/setup-node/tree/v3.4.0)`?

**Comment by dmitry-shibanov** [comment] 2022-07-14 19:28
Hello @ddzz. It was not fixed by this release because it looks like the issue from other side because the similar behaviour can be reproduced with other actions.
I think it is related issue: https://github.com/actions/runner/issues/1923

**Comment by dmitry-shibanov** [comment] 2022-07-15 12:39
Hello everyone. Does it still reproduce for you? According to the comment it should work as expected https://github.com/actions/runner/issues/1923#issuecomment-1182457281

**Comment by dmitry-shibanov** [comment] 2022-07-18 08:42
Hello everyone. For now It looks like the action works as expected. I'm going to close because according to the [comment](https://github.com/actions/runner/issues/1923#issuecomment-1182457281) the issue was fixed

**Closed by dmitry-shibanov** 2022-07-18 08:42 UTC
Labels: bug
