### ISSUE TITLE
npm install npm@version not working on the mac image

### ISSUE THREAD

**Issue by dougmoscrop** [actions/setup-node#31] opened 2019-08-15 19:53 UTC
It would be cool to optionally specify which version of npm is used regardless of the node version (use case: I am using AWS Lambda with the 8.10 runtime, but I want to use npm@6.7.0)

**Comment by damccorm** [comment] 2019-08-16 16:53
This is a fair suggestion, and one I've given some thought to, but I _think_ we're probably not going to do this. We've had some discussion surrounding this, but in general, we view the setup-* actions as actions to setup the tool but **not** the ecosystem around it - so the setup actions should work like node's installer executable does. Npm is a little bit of a tricky case because the installer packages npm with Node, so its not clear where the tool ends and the ecosystem starts. For now, though, we've decided to adopt the same behavior as the installer executable and not install different versions of npm and/or Yarn.

FWIW, I'm also a little less worried about this one because its relatively easy to fix - just add a step `run: npm install --global npm@6.7.0`. Again, this feels like the line that the Node installer draws.

Does that make sense/seem reasonable?

**Comment by dougmoscrop** [comment] 2019-08-16 17:05
It is reasonable and the first thing I tried, but it seemed like the global install worked but was not effective (so my next steps that ran still used the old version).

Maybe I did something wrong, but getting npm@6 using node 8.10 didn't work, like:

```sh
npm i -g npm@6
npm ci
```

failed with 'ci' not being a known command (it looked like npm@5 was still the one in effect)

**Comment by damccorm** [comment] 2019-08-16 17:22
Huh, that's weird. If that's not working, we definitely should fix that!

With that said, I'm not able to reproduce. Could you try running `npm -v` before/after doing the global install and see if we're getting the correct version of npm that way?

Also, if your repo is public would you mind sharing it?

**Comment by dougmoscrop** [comment] 2019-08-16 17:33
For sure, let me just make sure I didn't do something stupid.

**Comment by dougmoscrop** [comment] 2019-08-16 18:39
Here's an example:

https://github.com/dougmoscrop/serverless-plugin-log-subscription/pull/9/checks?check_run_id=195597827

Is it because I am doing this in separate steps?

**Comment by bryanmacfarlane** [comment] 2019-10-16 12:39
If there was a setup-npm or npm-version input, it would just run the command above that appears to be failing on the mac for some reason.  Steps do run out of process but it should be fine since that should change symlinks.

We don't have an npm-version property since (1) installing a node version by querying their json, happens to carry a version of npm and (2) if the version specified is different then it would just do npm -i npm@ver (so why not just do that)?

So I think the action item is to figure out why npm -i is not working on the mac image.

**Comment by dmitry-shibanov** [comment] 2021-11-12 15:02
Hello everyone. Sorry for the late response. I've tried to reproduce the issue, but it looks like nodejs version setting up by the action works as expected. If you use nodejs version from hosted images you can try to upgrade npm version with this command: `npm i -g npm --prefix=/usr/local/opt/node@14`

For now I'm closing the issue. We have similar issue with adding [npm-version input](https://github.com/actions/setup-node/issues/213). If you have any concerns feel free to contact us.

**Closed by dmitry-shibanov** 2021-11-12 15:02 UTC
Labels: external
