### ISSUE TITLE
Yarn cache not found

### ISSUE THREAD

**Issue by mrlubos** [actions/setup-node#453] opened 2022-03-30 19:23 UTC
**Description:**
Opening a pull request and pushing changes to it does not cache dependencies, even if the lock file hasn't been affected at all.

**Action version:**
v3.0.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

**Repro steps:**
Using a Github CI workflow that looks like this:

```yml
setup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup Node environment
        uses: actions/setup-node@v3.0.0
        with:
          cache: yarn
          node-version-file: .nvmrc

      - name: Install dependencies
        run: yarn install --frozen-lockfile
```

Produces this log file for setup-node action:

```
Run actions/setup-node@v3.0.0
  with:
    cache: yarn
    node-version-file: .nvmrc
    always-auth: false
    check-latest: false
    token: ***
Resolved .nvmrc as 16.14.[2](https://github.com/foo/runs/5759850063?check_suite_focus=true#step:3:2)
Found in cache @ /opt/hostedtoolcache/node/16.1[4](https://github.com/foo/runs/5759850063?check_suite_focus=true#step:3:4).2/x[6](https://github.com/foo/runs/5759850063?check_suite_focus=true#step:3:6)4
/usr/local/bin/yarn --version
1.22.1[8](https://github.com/foo/runs/5759850063?check_suite_focus=true#step:3:8)
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6

yarn cache is not found
```

**Expected behavior:**
Pushing to the same pull request should trigger a new run that uses dependencies from the previous run, regardless of its completion status.

**Actual behavior:**
Every commit causes `yarn install` to take multiple minutes due to missing cache

**Comment by dmitry-shibanov** [comment] 2022-03-31 07:55
Hello @mrlubos. Thank you for your report. I think it can be related to the cache scope:
 - https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache
 - https://github.com/actions/cache#cache-scopes
 
 If it's not relevant to you, could you please provide a public repository to reproduce the issue.

**Comment by mrlubos** [comment] 2022-03-31 15:24
@dmitry-shibanov Thank you for your reply! I believe I used to use `actions/cache` before `cache` became an option in `actions/setup-node`, now I am no longer using it. Given that, how would I answer either of the links you shared? I am not sure if I use v1 or v2 since I only have `actions/setup-node`. Or am I misunderstanding this and I should be still explicitly using `actions/cache` in my Github workflow?

**Comment by dmitry-shibanov** [comment] 2022-04-04 11:58
Hello @mrlubos, just a gentle ping.

**Comment by dmitry-shibanov** [comment] 2022-04-13 07:28
Hello @mrlubos. For now I'm going to close the issue, because it looks like the expected behaviour. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-04-13 07:28 UTC
Labels: bug
