### ISSUE TITLE
with:-parameters not taken in account?

### ISSUE THREAD

**Issue by tobsch** [actions/setup-node#86] opened 2019-11-10 14:59 UTC
Excuse me, I am pretty much of a newbie but do not understand why my job does not use the parameters I supply.

I want to publish to gpr, but it does not use the supplied registry url:
```
name: npm Package
on: [push]

jobs:
  publish-gpr:
    runs-on: ubuntu-16.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        registry-url: https://npm.pkg.github.com/
        scope: '@ramp106'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
```

Error:
```
...
npm ERR! 401 Unauthorized - PUT https://registry.npmjs.org/vue-components - You must be logged in to publish packages.
```

I literally used the example action and it does not run?

**Comment by tebriel** [comment] 2019-11-16 19:33
I tried setting `ACTIONS_RUNNER_DEBUG` to `true` in my secret store in my repo to see the debug logs [as documented](https://github.com/actions/toolkit/blob/master/docs/action-debugging.md#step-debug-logs) but when I downloaded the raw log archive (also when looking at the web logs) I did not see any debug statements. I'm running into the same error as above.

**Comment by xPaw** [comment] 2019-11-19 15:29
I seem to be running into the same problem.

https://github.com/thelounge/thelounge-theme-solarized/commit/b20b1b8d46e4e62b9736b52179a9d56752edb591/checks?check_suite_id=318433803#step:5:27

https://github.com/thelounge/thelounge-theme-solarized/blob/b20b1b8d46e4e62b9736b52179a9d56752edb591/.github/workflows/release.yml#L22-L26

NODE_AUTH_TOKEN secret is set.

**Comment by xPaw** [comment] 2019-11-26 20:35
Solved it, you must specify `registry-url`, otherwise it doesn't work.

```
- uses: actions/setup-node@v1
  with:
    registry-url: 'https://registry.npmjs.org'
```

**Comment by tebriel** [comment] 2019-11-26 22:44
@xPaw won't that publish it to NPM instead of GPR (GitHub Package Registry)?

**Comment by xPaw** [comment] 2019-11-26 22:50
You can set the registry URL to GPR. But it has to be set for npmrc to be created, looking at the code.

**Comment by dmitry-shibanov** [comment] 2021-11-11 12:42
Hello everyone. Sorry for the late response. Could you please try to use v2 tag. I've tried to reproduce the issue but it looks like everything works as expected. If it's still relevant to you could you please provide a public repository to reproduce the issue.

**Comment by dmitry-shibanov** [comment] 2021-11-29 09:23
Hello everyone. I'm going to close the issue, because I can not reproduce it. If you get any additional information feel free to ping us.

**Closed by dmitry-shibanov** 2021-11-29 09:23 UTC
Labels: bug
