### ISSUE TITLE
Caching packages dependencies in composite actions

### ISSUE THREAD

**Issue by sergei-startsev** [actions/setup-node#329] opened 2021-09-08 17:09 UTC
Caching packages dependencies doesn't work in [composite actions](https://docs.github.com/en/actions/creating-actions/creating-a-composite-action) today. Action composition allows to reduce duplication in workflows and make maintenance easier, however `setup-node` with `cache` option doesn't support them – cache is always not found.

```yml
runs:
  using: 'composite'
  steps:
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: yarn
```

```
/usr/local/bin/yarn --version
1.22.11
/usr/local/bin/yarn cache dir
/home/runner/.cache/yarn/v6
yarn cache is not found
```

**Comment by dmitry-shibanov** [comment] 2021-10-20 09:34
Hello @sergei-startsev . Thank you for your report. Could you please create a public repository to reproduce the issue. Besides, could you please check this [response](https://github.com/actions/cache/issues/638#issuecomment-942658195).

**Comment by dmitry-shibanov** [comment] 2021-11-15 10:42
Hello @sergei-startsev, just gentle ping.

**Comment by dmitry-shibanov** [comment] 2021-11-22 15:14
Hello @sergei-startsev. I've tried to reproduce you issue, but it looks like everything works as expected. I want to note that the setup-node action does not provide restore-key, that is why possibly the cache is not found.

For now I'm closing the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2021-11-22 15:14 UTC
Labels: bug
