### ISSUE TITLE
Fallback to default node version if .nvmrc file does not exist

### ISSUE THREAD

**Issue by Th3S4mur41** [actions/setup-node#613] opened 2022-10-27 14:38 UTC
**Description:**
Currently using a [node version file](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#node-version-file) results in an error if the configured file is not found.

e.g. using .nvmrc
```
- uses: actions/setup-node@v3
  with:
    node-version-file: '.nvmrc'
```
Fails with the following error
```
The specified node version file at: /__w/actions/actions/.nvmrc does not exist
```

**Justification:**
When reusing workflows in multiple repositories, it will happen that some of them don't require a specific node version and therefor have no `.nvmrc` file.

In such cases, instead of failing it would be better to throw a warning and fallback to the default node version

**Are you willing to submit a PR?**
Yes

**Comment by dmitry-shibanov** [comment] 2022-10-27 14:47
Hello @Th3S4mur41. Thank you for your feature request. I do not think it will be a right behaviour because if customers specify a path to nodejs's file they are sure that the file exists. Besides, throwing only a warning can lead to some unexpected behaviour when the project is supposed to be built with the exact node version.

**Comment by Th3S4mur41** [comment] 2022-10-28 07:40
Hey @dmitry-shibanov. You are absolutely right when you use the action local workflows that are in the same repository as the `.nvmrc`.
With both in the same repository, you can definitely make sure it exists.

In the case of reusable workflows (e.g. all workflows are in a dedicated actions repository of an organization) though, you cannot control that all repositories in the organization define an `.nvmrc` file which is my use case.

I have two repositories that cannot yet use `node 18` that was just declared LTS, and I have to force them down to `node 16` using `npmrc`.
All the other repositories are just fine using latest node or node LTS and therefor do not need an `.nvmrc` file.

So the current workaround is to have an additional job in the workflows to check if `.nvmrc` exists and if it does, only add the `node-version-file`.
But having native support for this use case would be nicer

**Comment by dmitry-shibanov** [comment] 2023-01-24 10:44
Hello @Th3S4mur41. I'm not sure it will be correct solution to add fallback to setup-node if the file is not found. I think it will be better to add check from your side on existing of `.nvmrc` file. For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2023-01-24 10:44 UTC
Labels: feature request
