### ISSUE TITLE
Error publishing to GHPR

### ISSUE THREAD

**Issue by jasonkarns** [actions/setup-node#234] opened 2021-02-06 20:30 UTC
```yml
  github-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          registry-url: 'https://npm.pkg.github.com'
      - run: npm publish --ignore-scripts
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

Almost verbatim from the readme for publishing to GHPR. Took out the node-version (which is documented as optional) because any is fine. Took out the npm install step because we have no deps, so there's nothing to install. Added --ignore-scripts to eliminate possibility of malicious scripts in prepack, etc.

Example failed run: https://github.com/bats-core/bats-core/runs/1846241181

Error message:

```
npm ERR! code E404
npm ERR! 404 Not Found - PUT https://registry.npmjs.org/bats - Not found
npm ERR! 404 
npm ERR! 404  'bats@1.3.0-alpha' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2021-02-06T20_19_12_105Z-debug.log
```

**Comment by jasonkarns** [comment] 2021-02-07 16:12
Same error with explicit `scope`: https://github.com/bats-core/bats-core/runs/1849493435?check_suite_focus=true

**Comment by jasonkarns** [comment] 2021-02-07 17:52
Snagged (for the thousandth time) by GHPR requiring packages to be scoped.

The number of times this has bitten me, despite _knowing it_ leads me to believe this setup-node action ought to be aware of and warning users against this problem. The action knows when the registry is set to GHPR; and knows if the package name isn't scoped. It could emit a warning annotation when that combination is present. Better yet, it could _change the package name_ to be scoped. This would facilitate more packages to be cross-published that presently can't be (without pain) because they are un-scoped on npmjs.

**Comment by dmitry-shibanov** [comment] 2021-12-17 15:28
Hello @jasonkarns. Thank you for your report. Could you please create a separate issue as feature request with your proposal. 
For now I'm going to close the issue, because it's the expected behaviour.

**Closed by dmitry-shibanov** 2021-12-17 15:28 UTC
