### ISSUE TITLE
Error: Unable to locate executable file: pnpm

### ISSUE THREAD

**Issue by TechQuery** [actions/setup-node#530] opened 2022-06-28 12:42 UTC
## Description

I was migrating my Yarn Project to PNPM, but my GitHub actions crashed with `actions/setup-node`.

## Action version

v2 & v3

## Platform
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

## Runner type
- [x] Hosted
- [ ] Self-hosted

## Tools version

PNPM 7.3.0

## Repro steps

My migration of Workflow YAML shown below:

```diff
name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
-                 cache: yarn
+                 cache: pnpm
            - name: Install & Build
-             run: yarn  &&  yarn build
+             run: pnpm i  &&  pnpm build
```

## Expected behavior

Actions run successfully as Yarn cached version

## Actual behavior

Error thrown:

> Found in cache @ /opt/hostedtoolcache/node/14.19.3/x64
> Error: Unable to locate executable file: pnpm. Please verify either the file path exists or the file can be found within a directory specified by the PATH environment variable. Also check the file mode to verify the file is executable.

If I disable PNPM cache and install PNPM manually, it works for now:

```diff
name: CI & CD
on:
    push:
        branches:
            - master
jobs:
    Build-and-Deploy:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 14
-                 cache: pnpm
+           - name: Install PNPM
+             run: npm i -g pnpm
            - name: Install & Build
              run: pnpm i  &&  pnpm build
```

**Comment by dmitry-shibanov** [comment] 2022-06-28 21:52
Hello @TechQuery. Thank you for your report. It's an expected behaviour because `pnpm` should be preinstalled before the setup-node action. Please refer to the [documentation](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) for pnpm caching.

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-06-28 21:52 UTC
Labels: bug, needs triage

**Comment by TechQuery** [comment] 2022-06-29 11:50
@dmitry-shibanov , thanks for your answer, I fixed it with the Advanced Document.

**Comment by landed1** [comment] 2024-12-30 10:30
> Hello @TechQuery. Thank you for your report. It's an expected behaviour because `pnpm` should be preinstalled before the setup-node action. Please refer to the [documentation](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-data) for pnpm caching.
> 
> For now I'm going to close the issue.

Thank you, can you explain how to do this please. I am new to this.

**Comment by TechQuery** [comment] 2024-12-30 13:48
> can you explain how to do this please. I am new to this.

Here is an example for new guys: https://github.com/EasyWebApp/WebCell/blob/8d1df6ef74c8d0839fc441044669ec6706cdd88b/.github/workflows/main.yml#L13-L24
