### ISSUE TITLE
`latest` option causes job to fail with no errors

### ISSUE THREAD

**Issue by abidbmt** [actions/setup-node#1135] opened 2024-09-17 18:31 UTC
**Description:**
Using `latest` in the `node-version` option makes the action return code 1 without any errors, not even with debug prints on

**Action version:**
4.0.3

**Platform:**
- [X] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [X] Hosted
- [ ] Self-hosted

**Tools version:**
N/A

**Repro steps:**  
Use `latest` in `node-version` option

**Expected behavior:**
Would run normally just as if you used `>=22` instead of `latest`

**Actual behavior:**
Job fails and returns code 1 with no errors
![image](https://github.com/user-attachments/assets/f8f666eb-8a7c-4503-93d4-e019e0499720)

 **Full workflow:**
```yaml
 name: Publish package to GitHub Packages
on:
  push:
    branches:
      - main
  release:
    types: [published]
jobs:
  build:
    if: ${{ ! contains(github.event.head_commit.message, '[skip ci]')}}
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4.1.7
      # Setup .npmrc file to publish to GitHub Packages
      - uses: actions/setup-node@v4.0.3
        with:
          node-version: 'latest'
          registry-url: 'https://npm.pkg.github.com'

      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

**Comment by ryanwitt** [comment] 2024-09-17 18:38
Note that nodejs.org is having an outage, though status.nodejs.org had not been updated as of just before this comment.

**Comment by priyagupta108** [comment] 2024-09-18 05:05
Hello @abidbmt 👋,
Thank you for reporting this issue. The issue was caused by a temporary outage on the Node.js website affecting downloads. According to the [Node.js status page](https://status.nodejs.org/), the issue has now been resolved. Please try rerunning your workflows. If the problem persists, feel free to reach out to us.

**Comment by priyagupta108** [comment] 2024-09-27 04:46
Hello @abidbmt,
The issue was caused by a temporary outage on the Node.js website, which has now been resolved. I will close this issue for now. If you continue to experience any problems, please feel free to reopen this issue or create a new one.
Thank you!

**Closed by priyagupta108** 2024-09-27 04:46 UTC
Labels: bug
