### ISSUE TITLE
permission issue causing failure to cache on windows

### ISSUE THREAD

**Issue by geemus** [actions/setup-node#1024] opened 2024-04-29 15:52 UTC
**Description:**
Post job cleanup fails with permission issues:

```
Post job cleanup.
"C:\Program Files\Git\usr\bin\tar.exe" --posix -cf cache.tzst --exclude cache.tzst -P -C D:/a/anchor/anchor --files-from manifest.txt --force-local --use-compress-program "zstd -T0"
/usr/bin/tar: C\:/npm/cache/_logs/2024-04-29T15_30_50_704Z-debug-0.log: Cannot open: Permission denied
/usr/bin/tar: C\:/npm/cache/_logs/2024-04-29T15_30_59_272Z-debug-0.log: Cannot open: Permission denied
/usr/bin/tar: Exiting with failure status due to previous errors
Warning: Failed to save: "C:\Program failed with error: The process 'C:\Program Files\Git\usr\bin\tar.exe' failed with exit code 2
```

**Action version:**
actions/setup-node@v4

**Platform:**
- [ ] Ubuntu
- [ ] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
node 20.10.0
npm (? I didn't specify, so the default I suppose)

**Repro steps:**  
Here are what I think would be the relevant bits from our setup:
```
      - name: Setup Node (prism)
        uses: actions/setup-node@v4
        with:
          cache: npm
          node-version-file: '.tool-versions'
      - run: npm install
```
I'll note that we just have a `package.json` and no lock at present in case that is relevant.

**Expected behavior:**
I expected the caching to "just work" with this setup, as it does with the same invocation on mac/ubuntu.

**Actual behavior:**
Setup node and the rest of the action work fine, but the cleanup/caching fails (so there is never a cache to be used).

**Comment by aparnajyothi-y** [comment] 2024-04-30 13:06
Hello @geemus, Thank you for creating this issue and we will look into it :)

**Comment by priya-kinthali** [comment] 2024-05-21 12:41
Hello @geemus 👋,
Thank you for sharing the details!
I tried to replicate the error using the provided code snippet, but was unable to do so. By default, the `actions/setup-node` action looks for a dependency `lock file` in your repository's root. If this file is not found, the setup step will fail. You can find more information in this [related document](https://github.com/actions/setup-node?tab=readme-ov-file#caching-global-packages-data). 
As I couldn't reproduce your issue, it would be really helpful if you could share a link to a minimal reproduction of the problem for further investigation. Thank you in advance:)

**Comment by geemus** [comment] 2024-05-21 17:20
Thanks for checking on this. I changed some things to ensure there is a lock file present, but it doesn't seem to have made a difference. FWIW we run the same jobs on mac and ubuntu and they worked fine both before and after (and everything but the cache save afterward seems to work on windows). I also tried to setup a minimal reproduction case, but so far I haven't figured out how to get it to fail (it seems to work just fine, probably similar to what you saw).

**Comment by priya-kinthali** [comment] 2024-05-30 10:36
Hello there👋,
Any luck creating a reproducible scenario? This would greatly help us in diagnosing and fixing the issue. Thanks in advance for your cooperation:)

**Comment by geemus** [comment] 2024-06-03 13:32
It's still happening consistently in our main repo, but I have been unable to extract the right mix of things to get it to reproduce elsewhere so far.

**Comment by priya-kinthali** [comment] 2024-06-07 15:08
Hello @geemus 👋,
Your efforts to create a minimal reproduction case are much appreciated:)
In the meantime, for troubleshooting purposes, please consider the following:
1. Review the permission settings for the directories and files being accessed during the cleanup process. The error messages suggest that there are difficulties opening certain log files due to permission constraints.
2. Confirm that no other processes are accessing the log files. Close any processes using these files prior to the start of the cleanup job. This is important because, on Unix-like systems like macOS and Ubuntu, file locking is advisory, meaning other processes can access a file even if it's already in use. Conversely, on Windows, file locking is mandatory, preventing other processes from accessing a file in use. The 'Permission denied' error typically arises in these scenarios.

Hope this helps!

**Comment by geemus** [comment] 2024-06-11 01:13
Thanks, those are good pointers. Since it is a monorepo, I wonder if perhaps other things are claiming a lock on that directory such as you suggest (like perhaps the go-setup stuff). I'll try to look at my reproduction efforts again and see if I can figure something out soon.

**Comment by geemus** [comment] 2024-06-17 14:54
I'll share the repo I made trying to repro in case that is helpful, but unfortunately I still haven't managed to get it to actually repro: https://github.com/anchordotdev/node-windows-repro

I think it's pretty similar to what is happening where we see the error with the exception that there we also are doing a go build after doing go setup. Not sure that this is helpful, but I'm also not sure what else to try so I thought I would share what I have so far in case it helps.

**Comment by priya-kinthali** [comment] 2024-07-03 11:57
Hello @geemus ,
Since the issue is not currently reproducible in the minimal reproduction case, I will be closing this issue for now. Please feel free to reopen this issue if you have additional information that could help us diagnose the issue more effectively.
Thank you for your understanding and cooperation!

**Closed** 2024-07-03 11:58 UTC
Labels: bug
