### ISSUE TITLE
Unexpected HTTP response: 500

### ISSUE THREAD

**Issue by jjtang1985** [actions/setup-node#133] opened 2020-04-06 09:20 UTC
Hi, here is our workflow:
```
jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
        node-version: [10.x, 11.x, 12.x]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
```
Could you please help solve the 500 issue?

#### error messages:
```
2020-04-06T08:56:36.9086235Z ##[group]Run actions/setup-node@v1
2020-04-06T08:56:36.9086378Z with:
2020-04-06T08:56:36.9086466Z   node-version: 11.x
2020-04-06T08:56:36.9086567Z   always-auth: false
2020-04-06T08:56:36.9086785Z ##[endgroup]
2020-04-06T08:56:37.5502432Z Unexpected HTTP response: 500
2020-04-06T08:56:37.5503835Z Waiting 17 seconds before trying again
2020-04-06T09:03:24.1481824Z Premature close
2020-04-06T09:03:24.1482863Z Waiting 13 seconds before trying again
2020-04-06T09:03:37.3152217Z ##[error]Unexpected HTTP response: 500
```

**Comment by Moumouls** [comment] 2020-04-06 09:26
Same in our workflows using node 12.x

**Comment by Raul6469** [comment] 2020-04-06 09:31
You can follow up in #132 ! Looks like we are a lot in this situation

**Comment by chingc** [comment] 2020-04-06 15:34
This isn't a setup-node issue.

The problem is coming from nodejs: https://github.com/nodejs/node/issues/32683

**Comment by bryanmacfarlane** [comment] 2020-04-07 15:31
Also this core issue also manifests itself in this issue: https://github.com/actions/setup-node/issues/132

I added details about the work we're doing in that issue which will cover both.

I'm going to close this one and leave the other open for discussions.

**Closed by bryanmacfarlane** 2020-04-07 15:31 UTC
