### ISSUE TITLE
can NOT find cache

### ISSUE THREAD

**Issue by guppy0356** [actions/setup-node#539] opened 2022-07-12 07:19 UTC
**Description:**
I created branch `node-cache-3` from branch `node-cache`. It means the branch `node-cache-3` has the base branch `node-cache`, doesn't it? In github docs, a branch can access to caches if its base branch creates caches.

> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main). For example, a cache created on the default branch would be accessible from any pull request. Also, if the branch feature-b has the base branch feature-a, a workflow triggered on feature-b would have access to caches created in the default branch (main), feature-a, and feature-b.

link: https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

The branch `node-cache-3` can NOT access to caches even if `node-cache` creates its caches in my repository.

link: https://github.com/guppy0356/gh-actions/runs/7296326981?check_suite_focus=true
link: https://github.com/guppy0356/gh-actions/runs/7296402979?check_suite_focus=true

**Action version:**
Specify the action version

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [ ] Self-hosted

I can't understand runner type is.

**Tools version:**

yarn 1.22.19
node v16.15.1

**Repro steps:**  

```
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'yarn'
```

**Expected behavior:**
The branch `node-cache-3` can access to caches created in the its base branch (`node-cache`).

**Actual behavior:**
The branch `node-cache-3` can NOT access to caches created in the its base branch (`node-cache`).

**Comment by vsafonkin** [comment] 2022-07-12 08:03
Hello @guppy0356, we will take a look at this.

**Comment by guppy0356** [comment] 2022-07-12 08:44
@vsafonkin 
Thank you for your respond. I think the caches created in default branch is accessible. It is expected.

**Comment by vsafonkin** [comment] 2022-07-12 11:03
Ok, I'm going to close this issue in this case.

**Comment by guppy0356** [comment] 2022-07-12 11:32
@vsafonkin 

no, no, no. please don't close this. The caches created in base branch has NOT been accessible.

**Comment by dmitry-shibanov** [comment] 2022-07-12 13:26
Hello @guppy0356. I think it's an expected behaviour because the cache looks for the default branch (it can be main). That is why when you create branch node-cache-3 from node-cache and the cache is different from the cache on the main branch it won't restore it.

**Comment by guppy0356** [comment] 2022-07-12 13:41
I am trying my best to understand your explanation. Given the following branches,

`main (no caches) -> node-cache(with caches) -> node-cache-3`

Do you mean the branch `node-cache-3` doesn't access to the caches created in branch `node-cache` because branch `main` has NO caches.

**Comment by guppy0356** [comment] 2022-07-12 13:41
@dmitry-shibanov 

I am trying my best to understand your explanation. Given the following branches,

`main (no caches) -> node-cache(with caches) -> node-cache-3`

Do you mean the branch `node-cache-3` doesn't access to the caches created in branch `node-cache` because branch `main` has NO caches.

**Comment by dmitry-shibanov** [comment] 2022-07-12 13:55
If I understand it uses the default branch for cache sharing (usually it is main branch). The cache from the main branch will be inherited to others (node-cache and node-cache-3). But if you change cache (update package-lock.json or something else to change primary key) the new branch won't inherit from other, that is why node-cache-3 can miss cache.

**Comment by guppy0356** [comment] 2022-07-12 14:01
@dmitry-shibanov 

Hmm..... In Github doc,

> A workflow can access and restore a cache created in the current branch, the base branch (including base branches of forked repositories), or the default branch (usually main). For example, a cache created on the default branch would be accessible from any pull request. Also, if the branch feature-b has the base branch feature-a, a workflow triggered on feature-b would have access to caches created in the default branch (main), feature-a, and feature-b.

It sounds like the branch `feature-b` can access to caches created in branch `feature-a`.

**Comment by dmitry-shibanov** [comment] 2022-07-12 16:23
Could you please try to use [actions/cache](https://github.com/actions/cache) ? I've tried to use `actions/cach`e and reproduced the same behaviour. Besides, could you please enable [debug logging](https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging) to check scope response from [toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache).

**Comment by guppy0356** [comment] 2022-07-13 13:34
@dmitry-shibanov 
Sorry for late answer because the time difference between your time and ours is very big. I'll try to debug now.

By the way, maybe I'm understanding it wrong about base branch. Following steps,

1. git checkout main
2. git checkout -b feature-a
3. git checkout -b feature-b

The branch `feature-b` has the base branch and its name is `feature-a`. This is correct, right?

**Comment by dmitry-shibanov** [comment] 2022-07-13 14:20
Hello @guppy0356. Yes, it's right. I tried to reproduce with similar steps.

**Comment by guppy0356** [comment] 2022-07-14 13:30
@dmitry-shibanov 
Okay, I understand about base branch, but I am still confused. I want to know the reason why the caches created in base branch doesn't shared.
I think this [issue](https://github.com/actions/cache/issues/823) mentioned same problem.

**Comment by dmitry-shibanov** [comment] 2022-07-18 08:38
Hello @guppy0356. Sorry for the late response. I'm not sure but I think the documentation can be wrong. I consider it's better to raise an issue in [actions/cache](https://github.com/actions/cache) repository to describe it for maintainers because the setup-node action uses the same package ([toolkit/cache](https://github.com/actions/toolkit/tree/main/packages/cache)) that `actions/cache` rely on.

For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2022-07-18 08:38 UTC
Labels: bug

**Comment by Christianjade1** [comment] 2022-07-18 19:51
Wow

**Comment by guppy0356** [comment] 2022-08-04 21:26
@dmitry-shibanov 
I've posted https://github.com/actions/cache/issues/877. I found documentation is wrong.
Thank you for your cooperation.
