### ISSUE TITLE
Fails without error on selfhosted runner 

### ISSUE THREAD

**Issue by dominik-fielmann** [actions/setup-node#203] opened 2020-10-21 11:35 UTC
I have deployed a self-hosted runner based on this docker image to my kubernetes cluster: https://github.com/myoung34/docker-github-actions-runner

The action fails, but I don't know why. This is the output:

```
Run actions/setup-node@v2.1.2
  with:
    node-version: 14.x
    registry-url: https://npm.pkg.github.com
    always-auth: false
    check-latest: false
    token: ***
Attempting to download 14.x...
Acquiring 14.14.0 from https://github.com/actions/node-versions/releases/download/14.14.0-310900524/node-14.14.0-linux-x64.tar.gz
```

Tried as well with node 12 and earlier versions of the action, same result.

I would expect at least some output what went wrong.

**Comment by dmitry-shibanov** [comment] 2021-11-11 12:40
Hello @dominik-fielmann, just a gentle ping.

**Comment by dmitry-shibanov** [comment] 2021-11-15 10:40
Hello @dominik-fielmann. I'm going to close the issue, because we can not reproduce it from our side. Please provide us with steps to reproduce the issue for further investigation.

**Closed by dmitry-shibanov** 2021-11-15 10:40 UTC
Labels: bug
