### ISSUE TITLE
Multiple cache stored

### ISSUE THREAD

**Issue by Renato66** [actions/setup-node#693] opened 2023-02-07 02:08 UTC
**Description:**
Action is creating cache for many runs 
<img width="481" alt="image" src="https://user-images.githubusercontent.com/9284273/217129110-f7e18aaa-8886-4d54-8a63-ae76eae626ed.png">

**Action version:**
actions/setup-node@v3

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
yarn

**Repro steps:**  

```yml

name: Check build

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Check lint
        run: yarn lint --max-warnings 0

      - name: Check build
        run: yarn build
 ```       

**Expected behavior:**
1 cache only as yarn lock didn't changed 

**Actual behavior:**
multiple cache with same name/size

**Comment by MaksimZhukov** [comment] 2023-02-07 08:26
Hello @Renato66 !
Thank you for reporting this! We will investigate the issue

**Comment by arkdelkaos** [comment] 2023-02-09 17:57
I have the same cache (same hash, same name) cloned for every branch that starts a new workflow. 
Like if it's unable to get the master/main cache, or any clone created by another branch, then procedes to make a new one for the current branch...and every new branch do the same: It only uses its own cache
To be honest, I was starting to think that maybe it was the expected behaviour for an action cache, until I saw this issue. Looking at the caches management, I'm having this problem for at least 4 days (I have no clone prior to that)

**Comment by MaksimZhukov** [comment] 2023-02-13 12:18
Hello @Renato66!
I could not reproduce the issue. Could you please provide us with the public repository where the issue occurs for further investigation?

**Comment by Renato66** [comment] 2023-02-13 12:21
It's not a public repository 😔

**Comment by Renato66** [comment] 2023-02-13 12:21
@arkdelkaos so you have any public repository with that?

**Comment by MaksimZhukov** [comment] 2023-02-17 10:40
@arkdelkaos just a gentle reminder

@Renato66 is it possible for you to create a simple public repository to reproduce the issue?

**Comment by matdave** [comment] 2023-03-03 16:44
I'm having the same issue on an also private repository.

**Comment by dmitry-shibanov** [comment] 2023-03-07 17:44
Hello everyone. Sorry for the late response. Could you please clarify some points:
- Was the cache generated under one branch or it was different branches ?
- Did you change yarn version ?

**Comment by matdave** [comment] 2023-03-08 17:12
@dmitry-shibanov it happens on pull request for me, so it's a "different branch". The yarn version for mine is the same.

**Comment by dmitry-shibanov** [comment] 2023-03-13 09:03
Hello everyone, just a gentle ping.

**Comment by matdave** [comment] 2023-03-13 16:57
I think you are right. However, I'm not sure of the solution. My brain is a little broken reading the examples, perhaps a side effect of Monday. Will look at this a bit further.

**Comment by matdave** [comment] 2023-03-14 17:05
After reading this, it looks like the way to get this working is having an action that generates the cache on the default branch, e.g. `main`. I've added a script to my main deploy that just generates a cache and will test this out.

**Comment by matdave** [comment] 2023-03-16 14:20
Adding an event to create the cache on the `main` branch has fixed it for me.

**Comment by arkdelkaos** [comment] 2023-03-24 07:14
Sorry, but I completely forgot about this topic.
The repository where I have the issue is also private 😔

I'm going to try the solution that @matdave mentioned by creating a cache against main 👍🏻

**Comment by matdave** [comment] 2023-03-24 19:55
@arkdelkaos is `master` set to your default branch on the repo?

**Comment by arkdelkaos** [comment] 2023-03-24 19:59
Yes, it's still named master instead of main

**Comment by dmitry-shibanov** [comment] 2023-04-03 13:21
Hello everyone. Thank you for all of your responses. I think the issue can't be fixed from setup-node side, because it is related to internal logic for child branches and cache inheritance. 
- https://github.com/actions/cache#cache-scopes
- https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#restrictions-for-accessing-a-cache

For now I'm going to close the issue. If you have any concerns feel free to ping us.

**Closed by dmitry-shibanov** 2023-04-03 13:21 UTC
Labels: bug
