### ISSUE TITLE
Node.js 16.x is not installing the latest LTS version

### ISSUE THREAD

**Issue by t1m0thyj** [actions/setup-node#562] opened 2022-08-23 20:23 UTC
**Description:**
Node.js 16.17 was released a week ago but installing `16.x` with the setup-node action still installs 16.16.

**Action version:**
v2 and v3

**Platform:**
- [x] Ubuntu
- [x] macOS
- [x] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**

n/a

**Repro steps:**  
Create and run a workflow that uses the setup-node action:
```
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
```
See [here](https://github.com/t1m0thyj/typescript-playground/runs/7981912256?check_suite_focus=true) for an example.

**Expected behavior:**
Node.js 16.17 should be installed.

**Actual behavior:**
Node.js 16.16 gets installed.

**Comment by dmitry-shibanov** [comment] 2022-08-23 21:51
Hello @t1m0thyj. Thank you for your report. It is an expected behaviour because the action firstly checks the hosted toolcache directory. You can try to specify a [check-latest](https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#check-latest-version) input to download the latest version from [node-versions](https://github.com/actions/node-versions).

For now I'm going to close the issue.

**Closed by dmitry-shibanov** 2022-08-23 21:51 UTC
Labels: bug
