### ISSUE TITLE
yarn global installed binary package is not executable?

### ISSUE THREAD

**Issue by JounQin** [actions/setup-node#85] opened 2019-11-10 10:12 UTC
https://github.com/rx-ts/babel-preset-proposal-typescript/commit/454f3d240e066c6e8dd1c224169f5b385a7bb126/checks?check_suite_id=303865307#step:7:67

**Comment by PaulRBerg** [comment] 2019-11-23 00:12
Also having this problem in my repo. Here's a [link](https://github.com/sablierhq/sablier-subgraph/commit/d42e6078af89453f1aac4983716376170fc92b97/checks?check_suite_id=325082451).

**Comment by PaulRBerg** [comment] 2019-11-23 00:16
Fwiw, switching to npm doesn't seem to be working either.

**Comment by olckara** [comment] 2020-01-29 08:17
I had the same problem and found a workaround for this:
- First I added a step to get yarn global bin directory
``` 
- name: Get yarn global bin directory
  id: yarn-bin
  run: echo "::set-output name=dir::$(yarn global bin)"
```
- Then I added this directory name as a prefix to my installed command
```
- name: Installing turtle-cli
   run: yarn global add turtle-cli@$TURTLE_VERSION
- name: Setting up environment for Turtle
   run: ${{ steps.yarn-bin.outputs.dir }}/turtle setup:$PLATFORM --sdk-version $EXPO_SDK_VERSION
```

**Comment by ajbarry** [comment] 2020-06-19 23:48
Oh I just found out about `::add-path`. Here is a another approach (firebase cli in my case) :
```
      - name: Install Firebase Tools
        run: |
          yarn global add firebase-tools
          echo "::add-path::$(yarn global bin)"
      - name: Jest Tests
        run: |
          firebase setup:emulators:firestore
          firebase use dev --token "${{ secrets.FIREBASE_TOKEN }}"
          yarn test
```
@olckara thanks for your workaround that lead me to the real problem

**Comment by kainoffke** [comment] 2020-10-23 09:34
It seems to work, if you use sudo:
```
 - name: Setup Serverless
      run: |
        sudo yarn global add  serverless
        serverless -v
```

**Comment by ajbarry** [comment] 2020-10-23 20:05
Thanks for the new hint @kainoffke 

My previous answer needs to be updated as GitHub has [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) the `add-path` command.

Now you would use the following for adding paths segments to subsequent steps in the workflow:
```
      - name: Install Firebase Tools
        run: |
          yarn global add firebase-tools
          echo "$(yarn global bin)" >> $GITHUB_PATH
      - name: Use Firebase Tools
        run: |
          firebase --version
```

**Comment by dmitry-shibanov** [comment] 2021-11-11 12:30
Hello everyone. For now I'm closing the issue, because the issue is no longer reproducible. If you have any concerns feel free to contact us.

**Closed by dmitry-shibanov** 2021-11-11 12:30 UTC
Labels: bug
