### ISSUE TITLE
Heavy cache miss count

### ISSUE THREAD

**Issue by iBotPeaches** [actions/setup-node#835] opened 2023-08-22 14:21 UTC
**Description:**
A large collection of "cache miss" and only a handful of "cache hit".

**Action version:**
`actions/setup-node@v3`

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [x] Hosted
- [ ] Self-hosted

**Tools version:**
```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
```

**Repro steps:**  
```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - run: npm ci --verbose
      shell: bash
```      

**Expected behavior:**
A restore of previously downloaded artifacts

**Actual behavior:**
```
npm http fetch GET 200 https://registry.npmjs.org/locate-path 2237ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-stable-stringify-without-jsonify 2232ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/yocto-queue/-/yocto-queue-0.1.0.tgz 777ms (cache hit)
npm http fetch GET 200 https://registry.npmjs.org/update-browserslist-db 2424ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/mime-types 2300ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/lodash.merge 2297ms (cache miss)
npm http fetch GET 200 https://registry.npmjs.org/json-schema-traverse 2291ms (cache miss)
npm http fetch GET 200 https://dl.fontawesome.com/signed/fontawesome-pro/npm/fortawesome/fontawesome-common-types/6.4.0/fortawesome-fontawesome-common-types-6.4.0.tgz?created=xxx&expires=xxx&source=xxx&signature=xxx 6157ms (cache miss)
```

* tons and tons of cache miss.

Like why was yocto-queue a hit but not fontawesome?

---

So this is being reported because you get charged for using bandwidth when using Font Awesome. Sadly in our case - the basic example used here does not properly cache all items and I'm not following why. We get a hit restoring the cache blob, but it appears its quite small to what I expect.

```
/home/runner/.npm
Received 24691139 of 24691139 (100.0%), 30.4 MBs/sec
Cache Size: ~24 MB (24691139 B)
Cache restored successfully
Cache restored from key: node-cache-Linux-npm-912ac010d33c9c8d3694535a04cbea9be930f020a6b09d60b707ae2ce2d4db8b
```

I know this action does NOT cache node_modules, but then I struggle to understand the benefit I'm gaining here. Its clearly caching and restoring something, but since it doesn't cache the thing that costs us money then :(

We then get billed for overages and Font Awesome support just tells us to follow [this guide](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows) which we clearly do.

<img width="733" alt="Screenshot 2023-08-22 at 10 14 02 AM" src="https://github.com/actions/setup-node/assets/611784/3ba181a8-8b11-4171-a8a2-42c0676fe884">

**Comment by iBotPeaches** [comment] 2023-08-22 19:11
So the large collection of misses was resolved by manually deleting/purging all the caches from that repository. The default cache key I assume is the lockfile hash, so why this happened - I'm not sure. Now the only thing not caching is the links from a private registry.

This private registry (Font Awesome) does not appear to ever successfully cache itself. I assume since the non node_modules cache is HTTP responses and these expire after 20 minutes. So the cache is respecting the TTL and thus becoming misses on builds.

I don't know if this means we should go back to rolling our own cache - (caching node_modules, skipping install if cache hit, etc) or just missing something here.

**Comment by dusan-trickovic** [comment] 2023-08-23 07:12
Hello, @iBotPeaches ! Thanks for reporting this issue, we will take a closer look and see what can be done :)

**Comment by codepuncher** [comment] 2023-10-09 13:29
I too am experiencing this same issue with FontAwesome. It is having a large impact on us and our budgets with overage charges.
We have many repositories that are facing this issue.

The only difference that I can see is that we are using `yarn` rather than `npm`.

**Comment by iBotPeaches** [comment] 2023-10-09 13:48
@codepuncher - I dug into this a lot with FA, who honestly just kept redirecting me back to official GitHub docs on caching. You can't really use setup-node, etc with FA Pro and expect to keep your bandwidth.

We mixed two forms of cache now.

```yaml
    - name: Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'npm'

    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: node_modules
        key: ${{ inputs.node-version }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: ${{ inputs.node-version }}-node-${{ hashFiles('**/package-lock.json') }}

    - run: npm ci
      if: steps.npm-cache.outputs.cache-hit != 'true'
      working-directory: ${{ inputs.directory }}
      shell: bash
```
(this is in a composite action)

We restore cache using regular setup-node, but then we attempt to restore a 1-1 cache based on the exact hash of the lock file. If we find a match for that, we skip `npm ci` - which is what would eventually hit FA Pro servers again and bleed bandwidth due to what I described above.

If that cache is a miss, we already restored the npm global cache (the 1st cache) so our cold/miss timing is still pretty fast as we are just installing the FA Pro, the private packages and whatever caused the miss (new version, etc)

This has kept us under the 2gb bandwidth limit for Sept.

**Comment by dsame** [comment] 2023-12-18 17:56
Hello @iBotPeaches,

The problem is not reproducible

1st run https://github.com/akv-demo/setup-node-test/actions/runs/7251833566/job/19755011576#step:4:9

```
Run npm ci --verbose
...
npm http fetch GET [20](https://github.com/akv-demo/setup-node-test/actions/runs/7251833566/job/19755011576#step:4:21)0 https://registry.npmjs.org/font-awesome/-/font-awesome-4.7.0.tgz 93ms (cache miss)
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 357ms
```

2nd run
```
Run npm ci --verbose
...
npm http fetch POST [20](https://github.com/akv-demo/setup-node-test/actions/runs/7251833566/job/19755025500#step:4:21)0 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 127ms
```

The idea of action is to cahce `~/.npm` directory which contains downloaded packages. Caching the node_modules does not seem a good idea because they its content can be out of sync.

It is impossible to find the exact reason why the `~/.npm` directory does not contain the whole bunch of packages but in the theory it can be caused the repository has outdated package-lock.json.

Did it help?

**Comment by iBotPeaches** [comment] 2023-12-18 18:22
Hi @dsame,

My experience was more for the Pro/Private option of FA, which does not appear to be cachable. Your test appears to be the public version of Font Awesome - so I don't think a true comparable replicable test.

I'm not saying my method is the cleanest, but it did solve our immediate problem of exceeding rate limits

<img width="823" alt="Screenshot 2023-12-18 at 1 21 09 PM" src="https://github.com/actions/setup-node/assets/611784/c667ea44-1917-40b2-8c9a-a84b515536e2">

Since my [comment](https://github.com/actions/setup-node/issues/835#issuecomment-1753052021) I've yet to hit a month where we exceed limits. I don't want to cache node_modules, but I did what I had to stay under usage limits.

**Comment by dsame** [comment] 2023-12-19 10:21
Hello @iBotPeaches, thank you for the clarification, i supposed there's something related to the private package and wanted to get the confirmation.

Nevertheless, it puzzles me with the dependencies from https://registry.npmjs.org are not cached as well despite I expect them to be stored in ~/.npm folder and cached.

I understand you've solved the problem with the workaround, but can you please double check does the build on the local host has to reload the awesomefonts npm with its dependencies? I still suspect the action has some flaw with the generating .npmrc config that might cause the problem. 

In case if the local build has the same problem or you don't have a time, please let us to close the issue with "it does not relate to the action"

**Comment by iBotPeaches** [comment] 2023-12-19 15:58
Hi @dsame,

I ran a few tests in a private repo like your configuration. With each change I got closer to our affected application, but each time I re-ran it - it seemed fine.

```
npm verb cli /opt/hostedtoolcache/node/18.19.0/x64/bin/node /opt/hostedtoolcache/node/18.19.0/x64/bin/npm
npm info using npm@10.2.3
npm info using node@v1[8](https://github.com/sourcetoad/actions-node-test/actions/runs/7264253745/job/19791375113#step:5:9).1[9](https://github.com/sourcetoad/actions-node-test/actions/runs/7264253745/job/19791375113#step:5:10).0
npm verb title npm ci
npm verb argv "ci" "--loglevel" "verbose"
npm verb logfile logs-max:[10](https://github.com/sourcetoad/actions-node-test/actions/runs/7264253745/job/19791375113#step:5:11) dir:/home/runner/.npm/_logs/2023-[12](https://github.com/sourcetoad/actions-node-test/actions/runs/7264253745/job/19791375113#step:5:13)-19T15_53_14_549Z-
npm verb logfile /home/runner/.npm/_logs/2023-12-19T15_53_14_549Z-debug-0.log
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 494ms
npm info run @fortawesome/fontawesome-common-types@6.5.1 postinstall node_modules/@fortawesome/fontawesome-common-types node attribution.js
npm info run @fortawesome/fontawesome-svg-core@6.5.1 postinstall node_modules/@fortawesome/fontawesome-svg-core node attribution.js
npm info run @fortawesome/fontawesome-common-types@6.5.1 postinstall { code: 0, signal: null }
npm info run @fortawesome/fontawesome-svg-core@6.5.1 postinstall { code: 0, signal: null }
```

```json
{
  "dependencies": {
    "@fortawesome/fontawesome-svg-core": "^6.5.1",
    "@fortawesome/pro-solid-svg-icons": "^6.5.1"
  }
}
```

```
@fortawesome:registry=https://npm.fontawesome.com
//npm.fontawesome.com/:_authToken=${FONTAWESOME_NPM_AUTH_TOKEN}
```

This worked fine. So I removed my workaround on the actual affected application and it was immediate misses again. Unfortunately the difference between the real affected application and this sample is 98,000~ different node packages.

So at this point - I can't replicate in my test, but my real application continues to replicate. I'm happy with a workaround, but I understand if you can't replicate - you can't fix.

I'll close this and if others stumble upon this with FA Pro and have the same bandwidth overage issue - maybe they can use my sample that works and/or discover the root cause themselves.

Thanks

**Comment by MostefaKamalLala** [comment] 2024-06-05 17:37
> @iBotPeaches / @dsame / @codepuncher - Is this issue still occurring using `actions/setup-node@v4`?

Occuring for me!

**Comment by aparnajyothi-y** [comment] 2024-11-25 03:26
Hello Everyone, Thank you for bringing this to our attention. We understand your concerns regarding Font Awesome and the caching behavior you're seeing.

Based on our investigation, we were unable to reproduce the issue you're experiencing with actions/setup-node@v4. The caching mechanism in actions/setup-node is designed to cache local npm dependencies (i.e., those fetched from the npm registry), but it does not extend to external resources like CDN assets. Since CDN resources such as Font Awesome are not part of the npm ecosystem, they aren't included in the npm cache and therefore are not cached by the GitHub Actions workflow.
Regarding your concern about npm dependencies from https://registry.npmjs.org not being cached as expected, please note that actions/setup-node caches the npm package cache (~/.npm), but it does not directly cache the node_modules directory. This means that dependencies fetched from the npm registry are cached in the npm cache folder, but they may not be restored directly into the node_modules folder on every run. If local caching is properly configured, there should be no need to reload Font Awesome (or other dependencies) on every build.
For more information on the caching behavior in GitHub Actions and actions/setup-node, you can refer to the following documentation:
[GitHub Actions Cache Documentation](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows)
[setup-node Action Documentation](https://github.com/actions/setup-node#caching)
We hope this helps clarify the caching behavior. Please feel free to reach out if you have any further questions or need additional assistance!

**Comment by gzurbach** [comment] 2024-11-26 01:10
Thank you @iBotPeaches for the suggested workaround. We will give it a try tomorrow. 

Our workaround was to use Kits as a way to reduce the significant bandwidth usage caused by our CI/CD because of pro icon packages. Our plan was to configure the Kit to include only the specific icons used in our project, which would have allowed us to uninstall the larger packages containing all icons. Unfortunately, this idea also proved to be a dead end since [Kits are not supported in React Native](https://github.com/FortAwesome/react-native-fontawesome/issues/150).

As a result, we're left with either caching the entire `node_modules` folder as you suggested, or disabling CI/CD entirely... for the sake of icons 🤷‍♂️ 

We hope this caching issue can be addressed soon.

**Comment by aparnajyothi-y** [comment] 2024-12-04 07:28
Hello @iBotPeaches, Thank you for your response, and apologies for the delay. You're absolutely right that the behavior around CDN assets like Font Awesome isn't fully addressed in the current documentation. It’s also true that the caching mechanism in actions/setup-node is primarily designed for npm dependencies, not node_modules and external CDN assets.

I’m glad to hear that your workaround caching node_modules alongside setup-node is working well for you. I agree that using a cold cache to handle potential misses is a solid approach, as it ensures both your npm dependencies and external assets are reliably available. However, please note that caching node_modules or external CDN assets (e.g., Font Awesome) is not implemented by default to avoid inconsistencies across environments (OS, Node.js versions).

We are actively working to update the documentation to provide more clarity on caching behaviors, and we’ll definitely consider your feedback when addressing future caching use cases.

If anything changes or you need further assistance, please don't hesitate to reach out.

**Comment by aparnajyothi-y** [comment] 2024-12-06 13:50
Hello @iBotPeaches, Thanks for the response! The setup-node action already keys the cache based on variables such as Node.js version, OS, and architecture. This ensures that the cache is environment-specific, helping to avoid issues with mismatched dependencies and improving cache hit rates across different Node.js versions and platforms.

We are proceeding to close this issue, but we will keep it open for a documentation update in the setup-node action.

**Closed by aparnajyothi-y** 2024-12-06 13:50 UTC
Labels: bug
