### ISSUE TITLE
Error: Some specified paths were not resolved, unable to cache dependencies.

### ISSUE THREAD

**Issue by varndellwagglebee** [actions/setup-node#745] opened 2023-04-25 12:04 UTC
**Description:**
Unable to cache dependencies even though my package-lock file path is correct.

File structure:
Repository: Design-LLC/GlyphEditor

folders:

- ui
   - GlyphEditor
     -  package-lock.json

**Action version:**
Specify the action version

**Platform:**
- [X ] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ X] Hosted
- [ ] Self-hosted

**Tools version:**
   npm

**Repro steps:**  
  steps:  
      - name: Checkout repo
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: '${{github.repository}}/ui/glypheditor/package-lock.json'
      - run: |
          npm ci
          npm run build --if-present
          #npm run test --if-present

Here is log information:

2023-04-25T11:54:31.0792644Z From https://github.com/Design-LLC/GlyphEditor
2023-04-25T11:54:31.0793404Z  * [new ref]         fae484da7fe9dce4baa3f521a90ea5e0ad7734f6 -> origin/develop
2023-04-25T11:54:31.0814643Z ##[endgroup]
2023-04-25T11:54:31.0815257Z ##[group]Determining the checkout info
2023-04-25T11:54:31.0816749Z ##[endgroup]
2023-04-25T11:54:31.0817344Z ##[group]Checking out the ref
2023-04-25T11:54:31.0821696Z [command]/usr/bin/git checkout --progress --force -B develop refs/remotes/origin/develop
2023-04-25T11:54:31.1017671Z Switched to a new branch 'develop'
2023-04-25T11:54:31.1018453Z branch 'develop' set up to track 'origin/develop'.
2023-04-25T11:54:31.1023813Z ##[endgroup]
2023-04-25T11:54:31.1061629Z [command]/usr/bin/git log -1 --format='%H'
2023-04-25T11:54:31.1088118Z 'fae484da7fe9dce4baa3f521a90ea5e0ad7734f6'
2023-04-25T11:54:31.1442532Z ##[group]Run actions/setup-node@v3
2023-04-25T11:54:31.1442782Z with:
2023-04-25T11:54:31.1442966Z   node-version: 18.x
2023-04-25T11:54:31.1443171Z   cache: npm
2023-04-25T11:54:31.1443523Z   cache-dependency-path: Design-LLC/GlyphEditor/ui/glypheditor/package-lock.json
2023-04-25T11:54:31.1443866Z   always-auth: false
2023-04-25T11:54:31.1444082Z   check-latest: false
2023-04-25T11:54:31.1444455Z   token: ***
2023-04-25T11:54:31.1444625Z env:
2023-04-25T11:54:31.1444829Z   AZURE_WEBAPP_NAME: glypheditor
2023-04-25T11:54:31.1445252Z   AZURE_WEBAPP_PACKAGE_PATH: /ui
2023-04-25T11:54:31.1445465Z   NODE_VERSION: 18.x
2023-04-25T11:54:31.1445675Z   BRANCH_NAME: develop
2023-04-25T11:54:31.1445892Z   BUILD_CONFIGURATION: Debug
2023-04-25T11:54:31.1446107Z   VERSION_SUFFIX: develop
2023-04-25T11:54:31.1446310Z   SLOT: staging
2023-04-25T11:54:31.1446497Z ##[endgroup]
2023-04-25T11:54:31.3761571Z Found in cache @ /opt/hostedtoolcache/node/18.16.0/x64
2023-04-25T11:54:31.3774598Z ##[group]Environment details
2023-04-25T11:54:36.9601061Z node: v18.16.0
2023-04-25T11:54:36.9601817Z npm: 9.5.1
2023-04-25T11:54:36.9602586Z yarn: 1.22.19
2023-04-25T11:54:36.9603396Z ##[endgroup]
2023-04-25T11:54:36.9612295Z [command]/opt/hostedtoolcache/node/18.16.0/x64/bin/npm config get cache
2023-04-25T11:54:37.3366216Z /home/runner/.npm
2023-04-25T11:54:37.3544383Z ##[error]Some specified paths were not resolved, unable to cache dependencies.
2023-04-25T11:54:37.3639409Z Post job cleanup.
2023-04-25T11:54:37.4678412Z [command]/usr/bin/git version
2023-04-25T11:54:37.4725342Z git version 2.40.0

**Expected behavior:**
to cache the dependency

**Actual behavior:**
##[error]Some specified paths were not resolved, unable to cache dependencies.

Also this works using Windows- latest but NOT UBUNTU-LATEST
      - name: Set up Node.js
        uses: actions/setup-node@v3.5.1
        with:
           node-version: ${{ env.NODE_VERSION }}
           cache: 'npm'
           cache-dependency-path: 'ui/${{env.AZURE_WEBAPP_NAME}}'

**Comment by dmitry-shibanov** [comment] 2023-04-25 23:17
Hello @varndellwagglebee. Thank you for your report. We'll take a look on it.

**Comment by dusan-trickovic** [comment] 2023-04-27 08:58
Hello, @varndellwagglebee! Thank you for creating this issue. I would like to let you know that we did manage to find a working solution for it. Namely, in your YML configuration, we suggest replacing cache-dependency-path: '${{github.repository}}/ui/glypheditor/package-lock.json' with cache-dependency-path: 'ui/glypheditor/package-lock.json' and later on switching to the directory where your package-lock is using the simple cd ui/glypheditor command in the run block.

However, this goes without saying that if you notice anything else or if another problem arises, please don't hesitate to create a new issue and let us know about it. Alternatively, if all is well, you can let us know in the replies as well. We appreciate your input! :)

**Comment by varndellwagglebee** [comment] 2023-05-01 17:30
Still no luck and I did confirm that the package-lock.json is there.

      - name: Set up Node.js
        uses: actions/setup-node@v3.6.0
        with:
           node-version: 18 
           cache: 'npm'
           cache-dependency-path: 'ui/glypheditor/package-lock.json'       
      - run: |
           npm ci
           npm run build --if-present
           #npm run test --if-present

**Comment by dusan-trickovic** [comment] 2023-05-03 09:28
Hello, @varndellwagglebee ! Thank you for your follow-up!

After a few tries at reproducing the issue with the provided repro steps, we weren't able to do so accurately with the current data and would like to ask you to please provide us with a little bit more context. Since your repository is likely private, we cannot access it, so it would be great if you could create a minimal test repository (preferably with similar directory structure) with your action workflow included. That way, we can take a closer look and, possibly, spot the culprit of the bug in your configuration.

We appreciate your time and cooperation :)

**Comment by dusan-trickovic** [comment] 2023-05-15 10:48
Hello, @varndellwagglebee ! I'm just giving you a little ping to see if there are any updates on your end - was your issue resolved? Thank you in advance for your answer :)

**Comment by varndellwagglebee** [comment] 2023-05-15 11:58
I restructured my project so that it could find the path.  Thanks for following up

**Comment by dusan-trickovic** [comment] 2023-05-15 12:45
I'm glad that fixed your problem :) I will close this issue, since it has been resolved, but feel free to reach out and open a new one in case of any future problems or questions regarding our software. Thank you!

**Closed** 2023-05-15 12:45 UTC
Labels: bug
